In [1]:
# %% [markdown]
# Notebook ETL – leitura em batch, validações e write-back

In [2]:
# %% [code]
import os
import sys
import logging
from dotenv import load_dotenv
from rich.console import Console
from rich.logging import RichHandler

# ── Ajuste do PYTHONPATH para permitir importar de logs/ ──────────────────
project_root = os.getcwd()  # supondo que o notebook esteja em /home/debrito/Documentos/etl_debrito
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from logs.logging_setup import get_logger  # importa o configurador unificado

# ── Carrega variáveis de ambiente de .env (opcional) ───────────────────────
load_dotenv()

# ── Configuração de logs no notebook ──────────────────────────────────────
console = Console(width=120)
root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)

# ── Atenção: NÃO remover handlers existentes (por exemplo, o FileHandler) ──
#for h in root_logger.handlers[:]:
#    root_logger.removeHandler(h)

# ── Cria apenas o RichHandler para console, mantendo o FileHandler intacto ─
rich_handler = RichHandler(
    console=console,
    rich_tracebacks=True,
    show_time=True,
    show_level=True,
    show_path=False,
    markup=True,
)
rich_handler.setLevel(logging.DEBUG)
rich_handler.setFormatter(
    logging.Formatter("%(asctime)s %(levelname)s %(name)s › %(message)s", datefmt="%H:%M:%S")
)
root_logger.addHandler(rich_handler)

# ── Logger específico para este notebook ──────────────────────────────────
log = get_logger(__name__)
log.debug("Logger configurado para o notebook (RichHandler + FileHandler ativos)")

17:38:38 DEBUG __main__ › Logger configurado para o notebook (RichHandler + FileHandler ativos)

17:38:38 DEBUG    17:38:38 DEBUG __main__ › Logger configurado para o notebook (RichHandler + FileHandler ativos)

In [3]:
#2 %% [code]
import math
import numpy as np
from typing import Any

def _to_json_safe(x: Any) -> Any:
    """
    Internal helper to convert arbitrary objects into JSON-safe primitives.
    """
    if x is None:
        return None
    if isinstance(x, (int, str, bool)):
        return x
    if isinstance(x, float):
        return None if math.isnan(x) or math.isinf(x) else x
    if isinstance(x, (np.integer,)):
        return int(x)
    if isinstance(x, (np.floating,)):
        return None if (math.isnan(x) or math.isinf(x)) else float(x)
    if isinstance(x, (list, tuple, set)):
        return [_to_json_safe(item) for item in x]
    if isinstance(x, dict):
        return {k: _to_json_safe(v) for k, v in x.items()}
    # Fallback: stringify anything else
    return str(x)

def json_safe(obj: Any) -> Any:
    """
    Recursively converts `obj` into structures 100% serializable to JSON.
    """
    return _to_json_safe(obj)

In [4]:
#3 %% [code]
# Flags de gravação (ajuste conforme necessidade)
WRITE_BACK_ORIGIN = True   # grava na aba-origem (meta*, tiktok*, …)
WRITE_BACK_DEST   = True   # grava nas abas-modelo (modelo*)
DRY_RUN_DEST      = False  # True = simula write-back destino

# Credenciais e identificador da planilha
CREDS_PATH     = os.getenv("GOOGLE_CREDS_PATH", "creds.json")
SPREADSHEET_ID = os.getenv(
    "GOOGLE_SHEET_ID",
    "1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg"
)

# Abas de origem a processar, agrupadas por plataforma
SHEET_NAMES = [
    # Meta (Facebook / Instagram)
    "metaGeral",
    "metaIdade",
    "metaGenero",
    "metaRegiao",
    "metaAlcance",
    # TikTok
    "tiktokGeral",
    "tiktokIdade",
    "tiktokGenero",
    "tiktokRegiao",
    "tiktokAlcance",
    # Pinterest
    "pinterestGeral",
    "pinterestGenero",
    "pinterestIdade",
    "pinterestRegiao",
    "pinterestAlcance",
    # LinkedIn
    "linkedinGeral",
    "linkedinRegiao",
    "linkedinAlcance",
    # Google Analytics
    "GAGeral",
]

In [5]:
#4
# %% [code]
import importlib

# módulos principais e helpers recarregados
import extract.sheets_fetcher               as sf_mod
import treat.treat_pipeline                 as tp_mod
import treat.platforms                      as platforms_mod
import treat.platforms.linkedin             as linkedin_mod
import treat.platforms.tiktok               as tiktok_mod
import treat.platforms.pinterest            as pinterest_mod
import treat.platforms.meta                 as meta_mod
import treat.platforms.ga                   as ga_mod
import load.origin_writer                   as ow_mod
import load.dest_writer                     as dw_mod
import treat.utils.renomeacoes              as rn_mod
import treat.utils.preview_links            as prev_mod
import treat.utils.atribuicoes_via_lookup   as atrib_mod
import treat.utils.substitute_origin_values as sub_mod
import treat.utils.preprocess_utils         as pre_mod
import treat.utils.geo_normalize            as geo_mod

# hot-reload de todos os módulos alterados durante o desenvolvimento
for m in (
    sf_mod,
    tp_mod,
    platforms_mod,
    linkedin_mod,
    tiktok_mod,
    pinterest_mod,
    meta_mod,
    ga_mod,
    ow_mod,
    dw_mod,
    rn_mod,
    prev_mod,
    atrib_mod,
    sub_mod,
    pre_mod,
    geo_mod,
):
    importlib.reload(m)

In [6]:
# %% [code]
# Cell 5: definição do helper run_etl_for_sheet
import pandas as pd
import gc
import json
from pprint import pp
from typing import Dict

from logs.logging_setup import get_logger
log = get_logger(__name__)

from extract.sheets_fetcher import SheetsFetcher
from treat.treat_pipeline import TreatPipeline
from treat.utils.renomeacoes import renomeacao_geral, renomear_colunas_origem_para_modelo
from treat.utils.campos_calculados import calcular_engajamento_total, gerar_id
from load.origin_writer import write_back_origin
from load.dest_writer import write_back_for_sheet

# Instância única do fetcher (retry/backoff/cache interno)
fetcher = SheetsFetcher(
    spreadsheet_id=SPREADSHEET_ID,
    creds_path=CREDS_PATH,
)

def run_etl_for_sheet(
    *,
    sheet: str,
    wb_origin_flag: bool,
    wb_dest_flag: bool,
    dry_run_dest: bool,
    preloaded_raw: pd.DataFrame,
) -> Dict[str, pd.DataFrame | dict]:
    """
    Executa o fluxo completo para uma aba e devolve:
      { "dest": DataFrame destino (ou vazio), "taxo": relatório de taxonomia }
    """
    # 1) Dados brutos já carregados
    df_raw = preloaded_raw

    # 2) Tratamento via pipeline
    pipeline = TreatPipeline(
        creds_path=CREDS_PATH,
        spreadsheet_id=SPREADSHEET_ID,
        sheet_name=sheet,
        mapping_renomeacao=renomeacao_geral,
        write_back=wb_origin_flag,
    )
    df_ok = pipeline.run(df_raw)

    # 3) Relatório de taxonomia
    taxo_report = getattr(pipeline, "_last_taxo_report", {})
    pp(json.dumps(taxo_report, default=str), width=120)



    # 5) Preparar DataFrame de destino (modelo)
    df_model = renomear_colunas_origem_para_modelo(df_ok, renomeacao_geral)
    df_model = calcular_engajamento_total(df_model)
    df_model["ID"] = df_model.apply(gerar_id, axis=1)

    # 6) Write-back de destino  ──────────────────────────────────────────────
    if sheet.lower().startswith("ga"):
        log.info("🔸 %s: write-back de destino ignorado (Google Analytics)", sheet)
        df_dest = pd.DataFrame()      # retorna DataFrame vazio
    else:
        df_dest = write_back_for_sheet(
            df_model,
            sheet_name     = sheet,
            creds_path     = CREDS_PATH,
            spreadsheet_id = SPREADSHEET_ID,
            write_back     = wb_dest_flag,
            dry_run        = dry_run_dest,
        )
        if df_dest is None:
            df_dest = pd.DataFrame()

    # 7) Retorno
    return {"dest": df_dest, "taxo": taxo_report}

17:38:38 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:38:38 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

In [7]:
# %% [code]
# Cell 6: Processamento em lote das abas (com logging via logs.logging_setup)
from contextlib import suppress
import gc
import pandas as pd
from tqdm.auto import tqdm

from logs.logging_setup import get_logger
log = get_logger(__name__)

from load.dest_writer import prefetch_meta

# 1) Leitura batch de todas as abas
all_raw = fetcher.get(SHEET_NAMES)

# 2) Copia cada DataFrame para não alterar in-place
all_raw = {name: df.copy() for name, df in all_raw.items()}

# 3) Registrar colunas originais de cada aba para debug
orig_columns_map = {name: df.columns.tolist() for name, df in all_raw.items()}
for name, cols in orig_columns_map.items():
    log.debug(f"Aba '{name}' colunas originais: {cols}")

# 4) Pré-busca de cabeçalhos e IDs das abas-modelo
prefetch_meta(fetcher, SPREADSHEET_ID)
log.info("📥 Prefetch meta concluído – começando processamento das abas")

# 5) Processamento aba a aba
results: dict[str, dict[str, object]] = {}

for sheet in tqdm(SHEET_NAMES, desc="Processando abas"):
    is_ga = sheet.lower().startswith("ga")
    if is_ga:
        log.info(f"🔸 {sheet}: apenas write-back de origem; destino será ignorado")

    out = run_etl_for_sheet(
        sheet           = sheet,
        wb_origin_flag  = WRITE_BACK_ORIGIN,
        wb_dest_flag    = WRITE_BACK_DEST,
        dry_run_dest    = DRY_RUN_DEST,
        preloaded_raw   = all_raw[sheet],
    )

    results[sheet] = {"dest": out["dest"], "taxo": out["taxo"]}
    log.debug(f"Aba '{sheet}' processada – resultados armazenados")

    gc.collect()

log.info("✅ Processamento de todas as abas concluído")

17:38:38 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['metaGeral!A:ZZ', 'metaIdade!A:ZZ', 'metaGenero!A:ZZ', 'metaRegiao!A:ZZ', 'metaAlcance!A:ZZ', 'tiktokGeral!A:ZZ', 'tiktokIdade!A:ZZ', 'tiktokGenero!A:ZZ', 'tiktokRegiao!A:ZZ', 'tiktokAlcance!A:ZZ', 'pinterestGeral!A:ZZ', 'pinterestGenero!A:ZZ', 'pinterestIdade!A:ZZ', 'pinterestRegiao!A:ZZ', 'pinterestAlcance!A:ZZ', 'linkedinGeral!A:ZZ', 'linkedinRegiao!A:ZZ', 'linkedinAlcance!A:ZZ', 'GAGeral!A:ZZ']

         INFO     17:38:38 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['metaGeral!A:ZZ',
                  'metaIdade!A:ZZ', 'metaGenero!A:ZZ', 'metaRegiao!A:ZZ', 'metaAlcance!A:ZZ', 'tiktokGeral!A:ZZ',
                  'tiktokIdade!A:ZZ', 'tiktokGenero!A:ZZ', 'tiktokRegiao!A:ZZ', 'tiktokAlcance!A:ZZ',
                  'pinterestGeral!A:ZZ', 'pinterestGenero!A:ZZ', 'pinterestIdade!A:ZZ', 'pinterestRegiao!A:ZZ',
                  'pinterestAlcance!A:ZZ', 'linkedinGeral!A:ZZ', 'linkedinRegiao!A:ZZ', 'linkedinAlcance!A:ZZ',
                  'GAGeral!A:ZZ']

17:38:38 DEBUG googleapiclient.discovery › URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchGet?ranges=metaGeral%21A%3AZZ&ranges=metaIdade%21A%3AZZ&ranges=metaGenero%21A%3AZZ&ranges=metaRegiao%21A%3AZZ&ranges=metaAlcance%21A%3AZZ&ranges=tiktokGeral%21A%3AZZ&ranges=tiktokIdade%21A%3AZZ&ranges=tiktokGenero%21A%3AZZ&ranges=tiktokRegiao%21A%3AZZ&ranges=tiktokAlcance%21A%3AZZ&ranges=pinterestGeral%21A%3AZZ&ranges=pinterestGenero%21A%3AZZ&ranges=pinterestIdade%21A%3AZZ&ranges=pinterestRegiao%21A%3AZZ&ranges=pinterestAlcance%21A%3AZZ&ranges=linkedinGeral%21A%3AZZ&ranges=linkedinRegiao%21A%3AZZ&ranges=linkedinAlcance%21A%3AZZ&ranges=GAGeral%21A%3AZZ&alt=json

         DEBUG    17:38:38 DEBUG googleapiclient.discovery › URL being requested: GET
                  https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batc
                  hGet?ranges=metaGeral%21A%3AZZ&ranges=metaIdade%21A%3AZZ&ranges=metaGenero%21A%3AZZ&ranges=metaRegiao%
                  21A%3AZZ&ranges=metaAlcance%21A%3AZZ&ranges=tiktokGeral%21A%3AZZ&ranges=tiktokIdade%21A%3AZZ&ranges=ti
                  ktokGenero%21A%3AZZ&ranges=tiktokRegiao%21A%3AZZ&ranges=tiktokAlcance%21A%3AZZ&ranges=pinterestGeral%2
                  1A%3AZZ&ranges=pinterestGenero%21A%3AZZ&ranges=pinterestIdade%21A%3AZZ&ranges=pinterestRegiao%21A%3AZZ
                  &ranges=pinterestAlcance%21A%3AZZ&ranges=linkedinGeral%21A%3AZZ&ranges=linkedinRegiao%21A%3AZZ&ranges=
                  linkedinAlcance%21A%3AZZ&ranges=GAGeral%21A%3AZZ&alt=json

17:38:38 DEBUG google_auth_httplib2 › Making request: POST https://oauth2.googleapis.com/token

         DEBUG    17:38:38 DEBUG google_auth_httplib2 › Making request: POST https://oauth2.googleapis.com/token

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGeral!A1:AB588

17:38:44 INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGeral!A1:AB588

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaIdade!A1:Q2140

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaIdade!A1:Q2140

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGenero!A1:T863

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGenero!A1:T863

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaRegiao!A1:Q10000

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaRegiao!A1:Q10000

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaAlcance!A1:N588

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaAlcance!A1:N588

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGeral!A1:W155

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGeral!A1:W155

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokIdade!A1:O747

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokIdade!A1:O747

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGenero!A1:O258

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGenero!A1:O258

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokRegiao!A1:O3024

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokRegiao!A1:O3024

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokAlcance!A1:L128

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokAlcance!A1:L128

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGenero!A1:M2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGenero!A1:M2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestIdade!A1:M2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestIdade!A1:M2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestRegiao!A1:M2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestRegiao!A1:M2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestAlcance!A1:N2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestAlcance!A1:N2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinGeral!A1:U2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinGeral!A1:U2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinRegiao!A1:M2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinRegiao!A1:M2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinAlcance!A1:J2

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinAlcance!A1:J2

17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: GAGeral!A1:X4693

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: GAGeral!A1:X4693

17:38:44 INFO extract.sheets_fetcher › 📡 batchGet 19 ranges

         INFO     17:38:44 INFO extract.sheets_fetcher › 📡 batchGet 19 ranges

17:38:44 DEBUG __main__ › Aba 'metaGeral' colunas originais: ['date', 'account_name', 'campaign_name', 'ad_group_name', 'ad_name', 'utm_content', 'ad_id', 'campaign_id', 'start', 'end', 'objective', 'preview_link_ig', 'preview_link_fb', 'placement', 'campaign_daily_budget', 'campaign_lifetime_budget', 'campaign_remaining_budget', 'impressions', 'cost', 'link_clicks', 'video_watched_25', 'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions', 'post_shares', 'post_comments', 'video_play']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'metaGeral' colunas originais: ['date', 'account_name', 'campaign_name',
                  'ad_group_name', 'ad_name', 'utm_content', 'ad_id', 'campaign_id', 'start', 'end', 'objective',
                  'preview_link_ig', 'preview_link_fb', 'placement', 'campaign_daily_budget',
                  'campaign_lifetime_budget', 'campaign_remaining_budget', 'impressions', 'cost', 'link_clicks',
                  'video_watched_25', 'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions',
                  'post_shares', 'post_comments', 'video_play']

17:38:44 DEBUG __main__ › Aba 'metaIdade' colunas originais: ['date', 'age', 'account_name', 'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'utm_content', 'ad_id', 'start', 'end', 'placement', 'impressions', 'cost', 'video_watched_100', 'link_clicks']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'metaIdade' colunas originais: ['date', 'age', 'account_name',
                  'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'utm_content', 'ad_id',
                  'start', 'end', 'placement', 'impressions', 'cost', 'video_watched_100', 'link_clicks']

17:38:44 DEBUG __main__ › Aba 'metaGenero' colunas originais: ['date', 'gender', 'account_name', 'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'placement', 'ad_id', 'utm_content', 'start', 'end', 'impressions', 'cost', 'video_watched_100', 'link_clicks', 'post_shares', 'post_comments', 'post_reactions']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'metaGenero' colunas originais: ['date', 'gender', 'account_name',
                  'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'placement', 'ad_id',
                  'utm_content', 'start', 'end', 'impressions', 'cost', 'video_watched_100', 'link_clicks',
                  'post_shares', 'post_comments', 'post_reactions']

17:38:44 DEBUG __main__ › Aba 'metaRegiao' colunas originais: ['date', 'region', 'account_name', 'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'placement', 'ad_id', 'utm_content', 'start', 'end', 'impressions', 'cost', 'video_watched_100', 'link_clicks']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'metaRegiao' colunas originais: ['date', 'region', 'account_name',
                  'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'placement', 'ad_id',
                  'utm_content', 'start', 'end', 'impressions', 'cost', 'video_watched_100', 'link_clicks']

17:38:44 DEBUG __main__ › Aba 'metaAlcance' colunas originais: ['date', 'account_name', 'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'utm_content', 'ad_id', 'start', 'end', 'placement', 'reach', 'impressions']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'metaAlcance' colunas originais: ['date', 'account_name',
                  'campaign_name', 'campaign_id', 'ad_name', 'ad_group_name', 'objective', 'utm_content', 'ad_id',
                  'start', 'end', 'placement', 'reach', 'impressions']

17:38:44 DEBUG __main__ › Aba 'tiktokGeral' colunas originais: ['date', 'account_name', 'campaign_name', 'ad_group_name', 'ad_name', 'campaign_id', 'start', 'end', 'objective', 'ad_preview_link', 'placement', 'utm_content', 'impressions', 'cost', 'link_clicks', 'video_play', 'video_watched_25', 'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions', 'post_shares', 'post_comments']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'tiktokGeral' colunas originais: ['date', 'account_name',
                  'campaign_name', 'ad_group_name', 'ad_name', 'campaign_id', 'start', 'end', 'objective',
                  'ad_preview_link', 'placement', 'utm_content', 'impressions', 'cost', 'link_clicks', 'video_play',
                  'video_watched_25', 'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions',
                  'post_shares', 'post_comments']

17:38:44 DEBUG __main__ › Aba 'tiktokIdade' colunas originais: ['date', 'age', 'account_name', 'campaign_name', 'campaign_id', 'ad_group_name', 'ad_name', 'objective', 'start', 'end', 'utm_content', 'impressions', 'cost', 'video_watched_100', 'link_clicks']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'tiktokIdade' colunas originais: ['date', 'age', 'account_name',
                  'campaign_name', 'campaign_id', 'ad_group_name', 'ad_name', 'objective', 'start', 'end',
                  'utm_content', 'impressions', 'cost', 'video_watched_100', 'link_clicks']

17:38:44 DEBUG __main__ › Aba 'tiktokGenero' colunas originais: ['date', 'account_name', 'campaign_id', 'campaign_name', 'ad_group_name', 'ad_name', 'objective', 'gender', 'utm_content', 'start', 'end', 'impressions', 'cost', 'link_clicks', 'video_watched_100']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'tiktokGenero' colunas originais: ['date', 'account_name',
                  'campaign_id', 'campaign_name', 'ad_group_name', 'ad_name', 'objective', 'gender', 'utm_content',
                  'start', 'end', 'impressions', 'cost', 'link_clicks', 'video_watched_100']

17:38:44 DEBUG __main__ › Aba 'tiktokRegiao' colunas originais: ['date', 'region', 'campaign_name', 'account_name', 'ad_name', 'campaign_id', 'ad_group_name', 'objective', 'utm_content', 'start', 'end', 'impressions', 'link_clicks', 'cost', 'video_watched_100']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'tiktokRegiao' colunas originais: ['date', 'region', 'campaign_name',
                  'account_name', 'ad_name', 'campaign_id', 'ad_group_name', 'objective', 'utm_content', 'start', 'end',
                  'impressions', 'link_clicks', 'cost', 'video_watched_100']

17:38:44 DEBUG __main__ › Aba 'tiktokAlcance' colunas originais: ['date', 'account_name', 'campaign_name', 'placement', 'ad_group_name', 'ad_name', 'objective', 'start', 'end', 'utm_content', 'reach', 'impressions']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'tiktokAlcance' colunas originais: ['date', 'account_name',
                  'campaign_name', 'placement', 'ad_group_name', 'ad_name', 'objective', 'start', 'end', 'utm_content',
                  'reach', 'impressions']

17:38:44 DEBUG __main__ › Aba 'pinterestGeral' colunas originais: ['date', 'account_name', 'campaign_name', 'ad_group_name', 'ad_name', 'campaign_id', 'start', 'end', 'objective', 'pin_id', 'placement', 'utm_content', 'impressions', 'cost', 'link_clicks', 'video_play', 'video_watched_25', 'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'pinterestGeral' colunas originais: ['date', 'account_name',
                  'campaign_name', 'ad_group_name', 'ad_name', 'campaign_id', 'start', 'end', 'objective', 'pin_id',
                  'placement', 'utm_content', 'impressions', 'cost', 'link_clicks', 'video_play', 'video_watched_25',
                  'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions']

17:38:44 DEBUG __main__ › Aba 'pinterestGenero' colunas originais: ['date', 'gender', 'account_name', 'campaign_name', 'campaign_id', 'objective', 'start', 'end', 'impressions', 'cost', 'video_watched_100', 'link_clicks', 'utm_content']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'pinterestGenero' colunas originais: ['date', 'gender', 'account_name',
                  'campaign_name', 'campaign_id', 'objective', 'start', 'end', 'impressions', 'cost',
                  'video_watched_100', 'link_clicks', 'utm_content']

17:38:44 DEBUG __main__ › Aba 'pinterestIdade' colunas originais: ['date', 'age', 'account_name', 'campaign_name', 'campaign_id', 'objective', 'start', 'end', 'impressions', 'cost', 'video_watched_100', 'link_clicks', 'utm_content']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'pinterestIdade' colunas originais: ['date', 'age', 'account_name',
                  'campaign_name', 'campaign_id', 'objective', 'start', 'end', 'impressions', 'cost',
                  'video_watched_100', 'link_clicks', 'utm_content']

17:38:44 DEBUG __main__ › Aba 'pinterestRegiao' colunas originais: ['date', 'region', 'campaign_name', 'account_name', 'campaign_id', 'objective', 'start', 'end', 'impressions', 'link_clicks', 'cost', 'video_watched_100', 'utm_content']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'pinterestRegiao' colunas originais: ['date', 'region', 'campaign_name',
                  'account_name', 'campaign_id', 'objective', 'start', 'end', 'impressions', 'link_clicks', 'cost',
                  'video_watched_100', 'utm_content']

17:38:44 DEBUG __main__ › Aba 'pinterestAlcance' colunas originais: ['date', 'account_name', 'campaign_name', 'ad_group_name', 'ad_name', 'objective', 'utm_content', 'start', 'end', 'reach', 'imrpessions', 'post_shares', 'post_comments', 'post_reactions']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'pinterestAlcance' colunas originais: ['date', 'account_name',
                  'campaign_name', 'ad_group_name', 'ad_name', 'objective', 'utm_content', 'start', 'end', 'reach',
                  'imrpessions', 'post_shares', 'post_comments', 'post_reactions']

17:38:44 DEBUG __main__ › Aba 'linkedinGeral' colunas originais: ['date', 'account_name', 'campaign_name', 'ad_name', 'campaign_id', 'start', 'end', 'objective', 'placement', 'utm_content', 'impressions', 'cost', 'link_clicks', 'video_play', 'video_watched_25', 'video_watched_50', 'video_watched_75', 'video_watched_100', 'post_reactions', 'post_shares', 'post_comments']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'linkedinGeral' colunas originais: ['date', 'account_name',
                  'campaign_name', 'ad_name', 'campaign_id', 'start', 'end', 'objective', 'placement', 'utm_content',
                  'impressions', 'cost', 'link_clicks', 'video_play', 'video_watched_25', 'video_watched_50',
                  'video_watched_75', 'video_watched_100', 'post_reactions', 'post_shares', 'post_comments']

17:38:44 DEBUG __main__ › Aba 'linkedinRegiao' colunas originais: ['date', 'account_name', 'campaign_id', 'campaign_name', 'objective', 'region', 'start', 'end', 'impressions', 'cost', 'link_clicks', 'video_watched_100', 'utm_content']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'linkedinRegiao' colunas originais: ['date', 'account_name',
                  'campaign_id', 'campaign_name', 'objective', 'region', 'start', 'end', 'impressions', 'cost',
                  'link_clicks', 'video_watched_100', 'utm_content']

17:38:44 DEBUG __main__ › Aba 'linkedinAlcance' colunas originais: ['date', 'account_name', 'campaign_name', 'campaign_id', 'objective', 'utm_content', 'start', 'end', 'reach', 'impressions']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'linkedinAlcance' colunas originais: ['date', 'account_name',
                  'campaign_name', 'campaign_id', 'objective', 'utm_content', 'start', 'end', 'reach', 'impressions']

17:38:44 DEBUG __main__ › Aba 'GAGeral' colunas originais: ['date', 'campaign_name', 'sessionSourceMedium', 'utm_content', 'region', 'totalUsers', 'sessions', 'averageSessionDuration', 'screenPageViews', 'engagedSessions', 'objective', 'Campanha', 'ID_Campanha', 'start', 'end', 'Veiculo', 'ID_Veiculo', 'ad_group_name', 'ad_name', 'post_shares', 'post_comments', 'post_reactions', 'Engajamento_Total', 'ID']

         DEBUG    17:38:44 DEBUG __main__ › Aba 'GAGeral' colunas originais: ['date', 'campaign_name',
                  'sessionSourceMedium', 'utm_content', 'region', 'totalUsers', 'sessions', 'averageSessionDuration',
                  'screenPageViews', 'engagedSessions', 'objective', 'Campanha', 'ID_Campanha', 'start', 'end',
                  'Veiculo', 'ID_Veiculo', 'ad_group_name', 'ad_name', 'post_shares', 'post_comments', 'post_reactions',
                  'Engajamento_Total', 'ID']

17:38:44 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['modeloGeral!A:ZZ', 'modeloGenero!A:ZZ', 'modeloIdade!A:ZZ', 'modeloAlcance!A:ZZ', 'modeloRegiao!A:ZZ']

         INFO     17:38:44 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['modeloGeral!A:ZZ',
                  'modeloGenero!A:ZZ', 'modeloIdade!A:ZZ', 'modeloAlcance!A:ZZ', 'modeloRegiao!A:ZZ']

17:38:44 DEBUG googleapiclient.discovery › URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchGet?ranges=modeloGeral%21A%3AZZ&ranges=modeloGenero%21A%3AZZ&ranges=modeloIdade%21A%3AZZ&ranges=modeloAlcance%21A%3AZZ&ranges=modeloRegiao%21A%3AZZ&alt=json

         DEBUG    17:38:44 DEBUG googleapiclient.discovery › URL being requested: GET
                  https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batc
                  hGet?ranges=modeloGeral%21A%3AZZ&ranges=modeloGenero%21A%3AZZ&ranges=modeloIdade%21A%3AZZ&ranges=model
                  oAlcance%21A%3AZZ&ranges=modeloRegiao%21A%3AZZ&alt=json

17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloGeral!A1:Z4693

17:38:45 INFO     17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloGeral!A1:Z4693

17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloGenero!A1:O52441

         INFO     17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloGenero!A1:O52441

17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloIdade!A1:O4030

         INFO     17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloIdade!A1:O4030

17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloAlcance!A1:L3700

         INFO     17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloAlcance!A1:L3700

17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloRegiao!A1:O35018

         INFO     17:38:45 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: modeloRegiao!A1:O35018

17:38:45 INFO extract.sheets_fetcher › 📡 batchGet 5 ranges

         INFO     17:38:45 INFO extract.sheets_fetcher › 📡 batchGet 5 ranges

17:38:45 INFO extract.sheets_fetcher › 📥 Cache hit para ('modeloAlcance', 'modeloGenero', 'modeloGeral', 'modeloIdade', 'modeloRegiao')

         INFO     17:38:45 INFO extract.sheets_fetcher › 📥 Cache hit para ('modeloAlcance', 'modeloGenero',
                  'modeloGeral', 'modeloIdade', 'modeloRegiao')

17:38:45 INFO load.dest_writer › 📥 Prefetch destino concluído: 5 abas com cabeçalho, total de IDs carregados=83

         INFO     17:38:45 INFO load.dest_writer › 📥 Prefetch destino concluído: 5 abas com cabeçalho, total de IDs
                  carregados=83

17:38:45 INFO __main__ › 📥 Prefetch meta concluído – começando processamento das abas

         INFO     17:38:45 INFO __main__ › 📥 Prefetch meta concluído – começando processamento das abas

Processando abas:   0%|          | 0/19 [00:00<?, ?it/s]

17:38:45 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:38:45 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:38:45 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:38:45 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:38:45 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:38:45 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:38:45 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

         DEBUG    17:38:45 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:38:45 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:38:45 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:38:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:46 DEBUG    17:38:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:38:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaGeral%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:38:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaGeral%27%21A1%3A1
                  HTTP/1.1" 200 None

17:38:46 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:38:46 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:38:46 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:38:46 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:38:46 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

         DEBUG    17:38:46 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:38:46 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:38:46 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:38:47 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:47 DEBUG    17:38:47 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:47 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:38:47 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27 HTTP/1.1" 200 None

17:38:48 DEBUG    17:38:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27
                  HTTP/1.1" 200 None

17:38:48 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028', '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044', '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021', '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061', '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041', '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064', '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150', '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146', '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152', '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149', '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144', '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140', '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155', '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177', '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

         WARNING  17:38:48 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028',
                  '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044',
                  '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021',
                  '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061',
                  '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041',
                  '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064',
                  '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150',
                  '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146',
                  '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152',
                  '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155',
                  '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177',
                  '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

17:38:48 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['SOURCE!A:ZZ']

         INFO     17:38:48 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['SOURCE!A:ZZ']

17:38:48 DEBUG googleapiclient.discovery › URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchGet?ranges=SOURCE%21A%3AZZ&alt=json

         DEBUG    17:38:48 DEBUG googleapiclient.discovery › URL being requested: GET
                  https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batc
                  hGet?ranges=SOURCE%21A%3AZZ&alt=json

17:38:48 DEBUG google_auth_httplib2 › Making request: POST https://oauth2.googleapis.com/token

         DEBUG    17:38:48 DEBUG google_auth_httplib2 › Making request: POST https://oauth2.googleapis.com/token

17:38:49 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: SOURCE!A1:Z999

17:38:49 INFO     17:38:49 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: SOURCE!A1:Z999

17:38:49 INFO extract.sheets_fetcher › 📡 batchGet 1 ranges

         INFO     17:38:49 INFO extract.sheets_fetcher › 📡 batchGet 1 ranges

17:38:49 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

         DEBUG    17:38:49 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

17:38:49 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:38:49 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:38:49 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 191433377 imp, 382044.06 cost

         INFO     17:38:49 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 191433377
                  imp, 382044.06 cost

17:38:49 WARNING treat.utils.validations › [Validação] Coluna 'preview_link_ig' vazia em 29 linha(s): 72, 73, 75, 78, 94, 96, 99, 106, 114, 128, …

         WARNING  17:38:49 WARNING treat.utils.validations › [Validação] Coluna 'preview_link_ig' vazia em 29 linha(s):
                  72, 73, 75, 78, 94, 96, 99, 106, 114, 128, …

17:38:49 WARNING treat.utils.validations › [Validação] Coluna 'campaign_daily_budget' vazia em 587 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:38:49 WARNING treat.utils.validations › [Validação] Coluna 'campaign_daily_budget' vazia em 587
                  linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:38:49 WARNING treat.utils.validations › [Validação] Coluna 'campaign_lifetime_budget' vazia em 305 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:38:49 WARNING treat.utils.validations › [Validação] Coluna 'campaign_lifetime_budget' vazia em 305
                  linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:38:49 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaGeral': 587 linhas × 28 colunas (com cabeçalho) = 16,464 células

         INFO     17:38:49 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaGeral': 587 linhas × 28
                  colunas (com cabeçalho) = 16,464 células

17:38:50 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:50 DEBUG    17:38:50 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:50 INFO load.origin_writer › ✅ Write-back concluído para 'metaGeral' (587 linhas × 28 colunas)

         INFO     17:38:50 INFO load.origin_writer › ✅ Write-back concluído para 'metaGeral' (587 linhas × 28 colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": ["2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028", '
 '"2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044", '
 '"2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021", '
 '"2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061", '
 '"2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041", '
 '"2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064", '
 '"2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150", '
 '"2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_CER_PAN0146", '
 '"2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_PAN0140", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155", '
 '"2025_3_BR_V\\u00cdDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0169", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0160", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0168", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RAFA_ACAO_DBT_SBRAE_2025_EMP_FEM0163", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0165", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0173", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0172", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0162", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0170", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0166", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0174", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0164", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VIC_ACAO_DBT_SBRAE_2025_EMP_FEM0167", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_ULTMOS_DIAS_ACAO_DBT_SBRAE_2025_CER_PAN0208"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:38:50 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:38:50 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:51 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:51 DEBUG    17:38:51 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:51 INFO load.dest_writer › ✅ Gravadas 587 linhas em 'modeloGeral'

         INFO     17:38:51 INFO load.dest_writer › ✅ Gravadas 587 linhas em 'modeloGeral'

17:38:51 DEBUG __main__ › Aba 'metaGeral' processada – resultados armazenados

         DEBUG    17:38:51 DEBUG __main__ › Aba 'metaGeral' processada – resultados armazenados

17:38:52 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:52 DEBUG    17:38:52 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:52 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaIdade%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:38:52 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaIdade%27%21A1%3A1
                  HTTP/1.1" 200 None

17:38:52 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028', '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044', '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021', '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061', '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041', '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064', '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150', '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146', '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152', '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149', '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144', '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140', '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155', '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177', '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

         WARNING  17:38:52 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028',
                  '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044',
                  '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021',
                  '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061',
                  '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041',
                  '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064',
                  '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150',
                  '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146',
                  '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152',
                  '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155',
                  '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177',
                  '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

17:38:52 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

         DEBUG    17:38:52 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

17:38:52 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:38:52 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:38:52 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 191433377 imp, 382043.92 cost

         INFO     17:38:52 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 191433377
                  imp, 382043.92 cost

17:38:52 WARNING treat.utils.validations › [Validação] Coluna 'video_watched_100' vazia em 1075 linha(s): 48, 70, 71, 72, 73, 74, 75, 78, 79, 80, …

         WARNING  17:38:52 WARNING treat.utils.validations › [Validação] Coluna 'video_watched_100' vazia em 1075
                  linha(s): 48, 70, 71, 72, 73, 74, 75, 78, 79, 80, …

17:38:52 WARNING treat.utils.validations › [Validação] Coluna 'link_clicks' vazia em 200 linha(s): 108, 109, 122, 123, 136, 137, 155, 161, 167, 205, …

         WARNING  17:38:52 WARNING treat.utils.validations › [Validação] Coluna 'link_clicks' vazia em 200 linha(s):
                  108, 109, 122, 123, 136, 137, 155, 161, 167, 205, …

17:38:52 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaIdade': 2139 linhas × 17 colunas (com cabeçalho) = 36,380 células

         INFO     17:38:52 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaIdade': 2139 linhas × 17
                  colunas (com cabeçalho) = 36,380 células

17:38:54 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:54 DEBUG    17:38:54 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:54 INFO load.origin_writer › ✅ Write-back concluído para 'metaIdade' (2139 linhas × 17 colunas)

         INFO     17:38:54 INFO load.origin_writer › ✅ Write-back concluído para 'metaIdade' (2139 linhas × 17 colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": ["2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028", '
 '"2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044", '
 '"2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021", '
 '"2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061", '
 '"2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041", '
 '"2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064", '
 '"2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150", '
 '"2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_CER_PAN0146", '
 '"2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_PAN0140", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155", '
 '"2025_3_BR_V\\u00cdDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0169", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0160", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0168", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RAFA_ACAO_DBT_SBRAE_2025_EMP_FEM0163", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0165", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0173", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0172", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0162", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0170", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0166", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0174", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0164", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VIC_ACAO_DBT_SBRAE_2025_EMP_FEM0167", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_ULTMOS_DIAS_ACAO_DBT_SBRAE_2025_CER_PAN0208"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:38:55 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:55 DEBUG    17:38:55 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:57 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:57 DEBUG    17:38:57 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:57 INFO load.dest_writer › ✅ Gravadas 2139 linhas em 'modeloIdade'

         INFO     17:38:57 INFO load.dest_writer › ✅ Gravadas 2139 linhas em 'modeloIdade'

17:38:57 DEBUG __main__ › Aba 'metaIdade' processada – resultados armazenados

         DEBUG    17:38:57 DEBUG __main__ › Aba 'metaIdade' processada – resultados armazenados

17:38:57 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:38:57 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:38:57 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaGenero%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:38:57 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaGenero%27%21A1%3A1
                  HTTP/1.1" 200 None

17:38:57 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028', '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044', '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021', '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061', '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041', '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064', '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150', '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146', '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152', '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149', '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144', '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140', '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155', '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177', '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

         WARNING  17:38:57 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028',
                  '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044',
                  '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021',
                  '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061',
                  '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041',
                  '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064',
                  '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150',
                  '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146',
                  '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152',
                  '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155',
                  '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177',
                  '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

17:38:58 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

17:38:58 DEBUG    17:38:58 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

17:38:58 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:38:58 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:38:58 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 191433377 imp, 382044.06 cost

         INFO     17:38:58 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 191433377
                  imp, 382044.06 cost

17:38:58 WARNING treat.utils.validations › [Validação] Coluna 'video_watched_100' vazia em 480 linha(s): 4, 5, 10, 11, 16, 17, 22, 23, 28, 29, …

         WARNING  17:38:58 WARNING treat.utils.validations › [Validação] Coluna 'video_watched_100' vazia em 480
                  linha(s): 4, 5, 10, 11, 16, 17, 22, 23, 28, 29, …

17:38:58 WARNING treat.utils.validations › [Validação] Coluna 'link_clicks' vazia em 105 linha(s): 64, 65, 111, 112, 113, 115, 119, 122, 125, 127, …

         WARNING  17:38:58 WARNING treat.utils.validations › [Validação] Coluna 'link_clicks' vazia em 105 linha(s): 64,
                  65, 111, 112, 113, 115, 119, 122, 125, 127, …

17:38:58 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaGenero': 862 linhas × 20 colunas (com cabeçalho) = 17,260 células

         INFO     17:38:58 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaGenero': 862 linhas × 20
                  colunas (com cabeçalho) = 17,260 células

17:38:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:59 DEBUG    17:38:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:38:59 INFO load.origin_writer › ✅ Write-back concluído para 'metaGenero' (862 linhas × 20 colunas)

         INFO     17:38:59 INFO load.origin_writer › ✅ Write-back concluído para 'metaGenero' (862 linhas × 20 colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": ["2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028", '
 '"2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044", '
 '"2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021", '
 '"2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061", '
 '"2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041", '
 '"2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064", '
 '"2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150", '
 '"2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_CER_PAN0146", '
 '"2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_PAN0140", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155", '
 '"2025_3_BR_V\\u00cdDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0169", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0160", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0168", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RAFA_ACAO_DBT_SBRAE_2025_EMP_FEM0163", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0165", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0173", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0172", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0162", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0170", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0166", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0174", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0164", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VIC_ACAO_DBT_SBRAE_2025_EMP_FEM0167", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_ULTMOS_DIAS_ACAO_DBT_SBRAE_2025_CER_PAN0208"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:38:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:38:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:00 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:00 DEBUG    17:39:00 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:00 INFO load.dest_writer › ✅ Gravadas 862 linhas em 'modeloGenero'

         INFO     17:39:00 INFO load.dest_writer › ✅ Gravadas 862 linhas em 'modeloGenero'

17:39:00 DEBUG __main__ › Aba 'metaGenero' processada – resultados armazenados

         DEBUG    17:39:00 DEBUG __main__ › Aba 'metaGenero' processada – resultados armazenados

17:39:01 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:01 DEBUG    17:39:01 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:01 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaRegiao%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:01 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaRegiao%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:01 WARNING treat.utils.validations › [Validação] 33 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028', '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044', '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021', '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061', '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041', '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064', '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150', '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146', '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152', '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149', '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144', '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140', '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155', '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177', '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

         WARNING  17:39:01 WARNING treat.utils.validations › [Validação] 33 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028',
                  '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044',
                  '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021',
                  '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061',
                  '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041',
                  '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064',
                  '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150',
                  '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146',
                  '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152',
                  '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155',
                  '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177',
                  '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

17:39:01 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

         DEBUG    17:39:01 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

17:39:01 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:01 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:01 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 106329839 imp, 205409.99 cost

         INFO     17:39:01 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 106329839
                  imp, 205409.99 cost

17:39:02 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaRegiao': 9999 linhas × 17 colunas (com cabeçalho) = 170,000 células

17:39:02 INFO     17:39:02 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaRegiao': 9999 linhas × 17
                  colunas (com cabeçalho) = 170,000 células

17:39:06 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:06 DEBUG    17:39:06 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:06 INFO load.origin_writer › ✅ Write-back concluído para 'metaRegiao' (9999 linhas × 17 colunas)

         INFO     17:39:06 INFO load.origin_writer › ✅ Write-back concluído para 'metaRegiao' (9999 linhas × 17
                  colunas)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": ["2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028", '
 '"2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044", '
 '"2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021", '
 '"2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061", '
 '"2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041", '
 '"2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064", '
 '"2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150", '
 '"2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_CER_PAN0146", '
 '"2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_PAN0140", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155", '
 '"2025_3_BR_V\\u00cdDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0169", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0160", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0168", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RAFA_ACAO_DBT_SBRAE_2025_EMP_FEM0163", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0165", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0173", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0172", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0162", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0170", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0166", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0174", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0164", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VIC_ACAO_DBT_SBRAE_2025_EMP_FEM0167"]}, "utm_content": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": []}}')

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)
17:39:07 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:07 DEBUG    17:39:07 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:12 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:12 DEBUG    17:39:12 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:12 INFO load.dest_writer › ✅ Gravadas 9999 linhas em 'modeloRegiao'

         INFO     17:39:12 INFO load.dest_writer › ✅ Gravadas 9999 linhas em 'modeloRegiao'

17:39:12 DEBUG __main__ › Aba 'metaRegiao' processada – resultados armazenados

         DEBUG    17:39:12 DEBUG __main__ › Aba 'metaRegiao' processada – resultados armazenados

17:39:13 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:13 DEBUG    17:39:13 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:13 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaAlcance%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:13 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27metaAlcance%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:13 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028', '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044', '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021', '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061', '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041', '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064', '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150', '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146', '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152', '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142', '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149', '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144', '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140', '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155', '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177', '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

         WARNING  17:39:13 WARNING treat.utils.validations › [Validação] 34 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028',
                  '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044',
                  '2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021',
                  '2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061',
                  '2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041',
                  '2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064',
                  '2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150',
                  '2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_CER_PAN0146',
                  '2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152',
                  '2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142',
                  '2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRIÇÕES_ACAO_DBT_SBRAE_2025_PAN0140',
                  '2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155',
                  '2025_3_BR_VÍDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177',
                  '2025_3_BR_VÍDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161'] …

17:39:13 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

         DEBUG    17:39:13 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_e_id_meta

17:39:13 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:13 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:13 WARNING treat.utils.validations › [Validação] Coluna 'cost' ausente em df_raw ou df_ok; pulando aggregate check

         WARNING  17:39:13 WARNING treat.utils.validations › [Validação] Coluna 'cost' ausente em df_raw ou df_ok;
                  pulando aggregate check

17:39:13 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaAlcance': 587 linhas × 14 colunas (com cabeçalho) = 8,232 células

         INFO     17:39:13 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'metaAlcance': 587 linhas × 14
                  colunas (com cabeçalho) = 8,232 células

17:39:14 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:14 DEBUG    17:39:14 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:14 INFO load.origin_writer › ✅ Write-back concluído para 'metaAlcance' (587 linhas × 14 colunas)

         INFO     17:39:14 INFO load.origin_writer › ✅ Write-back concluído para 'metaAlcance' (587 linhas × 14
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": ["2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0028", '
 '"2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0044", '
 '"2025_3_BR_STORIES_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0021", '
 '"2025_3_BR_STORIES_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0061", '
 '"2025_3_BR_STORIES_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0041", '
 '"2025_3_BR_STORIES_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0057", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0056", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0064", '
 '"2025_3_BR_CARD_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0150", '
 '"2025_3_BR_CARD_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_CER_PAN0146", '
 '"2025_3_BR_CARD_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0152", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0153", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0142", '
 '"2025_3_BR_CARD_CERRADO_QUEM_PODE_PARTICIPAR_ACAO_DBT_SBRAE_2025_CER_PAN0149", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_COMO_SE_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0144", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_DIA_DAS_INSCRI\\u00c7\\u00d5ES_ACAO_DBT_SBRAE_2025_PAN0140", '
 '"2025_3_BR_CARD_PANTANAL_CERRADO_MOTIVOS_PARA_INSCREVER_ACAO_DBT_SBRAE_2025_CER_PAN0145", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0155", '
 '"2025_3_BR_V\\u00cdDEO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0177", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0161", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_DANIELLE_ACAO_DBT_SBRAE_2025_EMP_FEM0169", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0160", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_LUIZA_ACAO_DBT_SBRAE_2025_EMP_FEM0168", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RAFA_ACAO_DBT_SBRAE_2025_EMP_FEM0163", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0165", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_RITA_ACAO_DBT_SBRAE_2025_EMP_FEM0173", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0172", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0162", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VALERIA_ACAO_DBT_SBRAE_2025_EMP_FEM0170", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0166", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VERONICA_ACAO_DBT_SBRAE_2025_EMP_FEM0174", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_TASSIA_ACAO_DBT_SBRAE_2025_EMP_FEM0164", '
 '"2025_3_BR_V\\u00cdDEO_CARTAS_VIC_ACAO_DBT_SBRAE_2025_EMP_FEM0167", '
 '"2025_3_BR_CARD_CERRADO_PANTANAL_ULTMOS_DIAS_ACAO_DBT_SBRAE_2025_CER_PAN0208"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:39:15 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:15 DEBUG    17:39:15 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:15 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:15 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:15 INFO load.dest_writer › ✅ Gravadas 587 linhas em 'modeloAlcance'

         INFO     17:39:15 INFO load.dest_writer › ✅ Gravadas 587 linhas em 'modeloAlcance'

17:39:15 DEBUG __main__ › Aba 'metaAlcance' processada – resultados armazenados

         DEBUG    17:39:15 DEBUG __main__ › Aba 'metaAlcance' processada – resultados armazenados

17:39:16 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:16 DEBUG    17:39:16 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:16 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokGeral%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:16 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokGeral%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:16 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL + PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

         WARNING  17:39:16 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +
                  PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

17:39:16 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069', '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199', '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197', '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

         WARNING  17:39:16 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069',
                  '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199',
                  '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197',
                  '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

17:39:16 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:16 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:16 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 93589875 imp, 368647.81 cost

         INFO     17:39:16 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 93589875
                  imp, 368647.81 cost

17:39:16 WARNING treat.utils.validations › [Validação] Coluna 'ad_preview_link' vazia em 3 linha(s): 38, 45, 52

         WARNING  17:39:16 WARNING treat.utils.validations › [Validação] Coluna 'ad_preview_link' vazia em 3 linha(s):
                  38, 45, 52

17:39:16 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 3 linha(s): 38, 45, 52

         WARNING  17:39:16 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 3 linha(s):
                  38, 45, 52

17:39:16 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokGeral': 154 linhas × 23 colunas (com cabeçalho) = 3,565 células

         INFO     17:39:16 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokGeral': 154 linhas × 23
                  colunas (com cabeçalho) = 3,565 células

17:39:17 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:17 DEBUG    17:39:17 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:17 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokGeral' (154 linhas × 23 colunas)

         INFO     17:39:17 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokGeral' (154 linhas × 23
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": ["\\"2025_3_BR_ALC_CPM_BRASIL, 18+, '
 'POPULA\\u00c7\\u00c3O EM GERAL + PERSONA \\"\\"DONAS DE PEQUENOS NEG\\u00d3CIOS\\"\\" + COBERTURA DE PALAVRAS-CHAVE '
 'RELACIONADAS\\""]}, "ad_name": {"missing_column": false, "empty_count": 0, "unknown_values": '
 '["2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:39:17 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:17 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:17 INFO load.dest_writer › ✅ Gravadas 153 linhas em 'modeloGeral'

         INFO     17:39:17 INFO load.dest_writer › ✅ Gravadas 153 linhas em 'modeloGeral'

17:39:17 DEBUG __main__ › Aba 'tiktokGeral' processada – resultados armazenados

         DEBUG    17:39:17 DEBUG __main__ › Aba 'tiktokGeral' processada – resultados armazenados

17:39:18 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:18 DEBUG    17:39:18 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:19 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokIdade%27%21A1%3A1 HTTP/1.1" 200 None

17:39:19 DEBUG    17:39:19 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokIdade%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:19 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL + PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

         WARNING  17:39:19 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +
                  PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

17:39:19 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069', '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199', '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197', '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

         WARNING  17:39:19 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069',
                  '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199',
                  '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197',
                  '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

17:39:19 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:19 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:19 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 93680723 imp, 368769.00 cost

         INFO     17:39:19 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 93680723
                  imp, 368769.00 cost

17:39:19 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 746 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:19 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 746 linha(s):
                  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:39:19 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokIdade': 746 linhas × 15 colunas (com cabeçalho) = 11,205 células

         INFO     17:39:19 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokIdade': 746 linhas × 15
                  colunas (com cabeçalho) = 11,205 células

17:39:20 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:20 DEBUG    17:39:20 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:20 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokIdade' (746 linhas × 15 colunas)

         INFO     17:39:20 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokIdade' (746 linhas × 15
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": ["\\"2025_3_BR_ALC_CPM_BRASIL, 18+, '
 'POPULA\\u00c7\\u00c3O EM GERAL + PERSONA \\"\\"DONAS DE PEQUENOS NEG\\u00d3CIOS\\"\\" + COBERTURA DE PALAVRAS-CHAVE '
 'RELACIONADAS\\""]}, "ad_name": {"missing_column": false, "empty_count": 0, "unknown_values": '
 '["2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:39:20 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:20 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:20 INFO load.dest_writer › ✅ Gravadas 746 linhas em 'modeloIdade'

         INFO     17:39:20 INFO load.dest_writer › ✅ Gravadas 746 linhas em 'modeloIdade'

17:39:20 DEBUG __main__ › Aba 'tiktokIdade' processada – resultados armazenados

         DEBUG    17:39:20 DEBUG __main__ › Aba 'tiktokIdade' processada – resultados armazenados

17:39:23 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:23 DEBUG    17:39:23 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:23 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokGenero%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:23 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokGenero%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:23 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL + PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

         WARNING  17:39:23 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +
                  PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

17:39:23 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069', '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199', '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197', '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

         WARNING  17:39:23 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069',
                  '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199',
                  '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197',
                  '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

17:39:23 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:23 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:23 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 93589875 imp, 368647.81 cost

         INFO     17:39:23 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 93589875
                  imp, 368647.81 cost

17:39:23 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 257 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:23 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 257 linha(s):
                  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:39:23 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokGenero': 257 linhas × 15 colunas (com cabeçalho) = 3,870 células

         INFO     17:39:23 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokGenero': 257 linhas ×
                  15 colunas (com cabeçalho) = 3,870 células

17:39:24 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:24 DEBUG    17:39:24 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:24 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokGenero' (257 linhas × 15 colunas)

         INFO     17:39:24 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokGenero' (257 linhas × 15
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": ["\\"2025_3_BR_ALC_CPM_BRASIL, 18+, '
 'POPULA\\u00c7\\u00c3O EM GERAL + PERSONA \\"\\"DONAS DE PEQUENOS NEG\\u00d3CIOS\\"\\" + COBERTURA DE PALAVRAS-CHAVE '
 'RELACIONADAS\\""]}, "ad_name": {"missing_column": false, "empty_count": 0, "unknown_values": '
 '["2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:39:25 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:25 DEBUG    17:39:25 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:25 INFO load.dest_writer › ✅ Gravadas 257 linhas em 'modeloGenero'

         INFO     17:39:25 INFO load.dest_writer › ✅ Gravadas 257 linhas em 'modeloGenero'

17:39:25 DEBUG __main__ › Aba 'tiktokGenero' processada – resultados armazenados

         DEBUG    17:39:25 DEBUG __main__ › Aba 'tiktokGenero' processada – resultados armazenados

17:39:26 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:26 DEBUG    17:39:26 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:26 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokRegiao%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:26 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokRegiao%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:26 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL + PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

         WARNING  17:39:26 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +
                  PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

17:39:26 WARNING treat.utils.validations › [Validação] 6 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069', '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199', '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197', '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198']

         WARNING  17:39:26 WARNING treat.utils.validations › [Validação] 6 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069',
                  '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199',
                  '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197',
                  '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198']

17:39:26 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:26 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:26 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 85925942 imp, 351383.54 cost

         INFO     17:39:26 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 85925942
                  imp, 351383.54 cost

17:39:26 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 3023 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:26 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 3023 linha(s):
                  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:39:26 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokRegiao': 3023 linhas × 15 colunas (com cabeçalho) = 45,360 células

         INFO     17:39:26 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokRegiao': 3023 linhas ×
                  15 colunas (com cabeçalho) = 45,360 células

17:39:28 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:28 DEBUG    17:39:28 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:28 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokRegiao' (3023 linhas × 15 colunas)

         INFO     17:39:28 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokRegiao' (3023 linhas × 15
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": ["\\"2025_3_BR_ALC_CPM_BRASIL, 18+, '
 'POPULA\\u00c7\\u00c3O EM GERAL + PERSONA \\"\\"DONAS DE PEQUENOS NEG\\u00d3CIOS\\"\\" + COBERTURA DE PALAVRAS-CHAVE '
 'RELACIONADAS\\""]}, "ad_name": {"missing_column": false, "empty_count": 0, "unknown_values": '
 '["2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198"]}, "utm_content": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": []}}')

17:39:30 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:30 DEBUG    17:39:30 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:30 INFO load.dest_writer › ✅ Gravadas 3023 linhas em 'modeloRegiao'

         INFO     17:39:30 INFO load.dest_writer › ✅ Gravadas 3023 linhas em 'modeloRegiao'

17:39:30 DEBUG __main__ › Aba 'tiktokRegiao' processada – resultados armazenados

         DEBUG    17:39:30 DEBUG __main__ › Aba 'tiktokRegiao' processada – resultados armazenados

17:39:31 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:31 DEBUG    17:39:31 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:31 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokAlcance%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:31 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27tiktokAlcance%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:31 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL + PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

         WARNING  17:39:31 WARNING treat.utils.validations › [Validação] 1 valor(es) de 'ad_group_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +
                  PERSONA ""DONAS DE PEQUENOS NEGÓCIOS"" + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"']

17:39:31 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069', '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199', '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197', '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202', '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

         WARNING  17:39:31 WARNING treat.utils.validations › [Validação] 8 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069',
                  '2025_3_BR_VÍDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199',
                  '2025_3_BR_VÍDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197',
                  '2025_3_BR_VÍDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202',
                  '2025_3_BR_VÍDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201']

17:39:31 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:31 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:31 WARNING treat.utils.validations › [Validação] Coluna 'cost' ausente em df_raw ou df_ok; pulando aggregate check

         WARNING  17:39:31 WARNING treat.utils.validations › [Validação] Coluna 'cost' ausente em df_raw ou df_ok;
                  pulando aggregate check

17:39:31 WARNING treat.utils.validations › [Validação] Coluna 'placement' vazia em 3 linha(s): 38, 45, 52

         WARNING  17:39:31 WARNING treat.utils.validations › [Validação] Coluna 'placement' vazia em 3 linha(s): 38, 45,
                  52

17:39:31 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 127 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:31 WARNING treat.utils.validations › [Validação] Coluna 'URL_do_Anuncio' vazia em 127 linha(s):
                  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:39:31 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokAlcance': 127 linhas × 12 colunas (com cabeçalho) = 1,536 células

         INFO     17:39:31 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'tiktokAlcance': 127 linhas ×
                  12 colunas (com cabeçalho) = 1,536 células

17:39:32 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:32 DEBUG    17:39:32 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:32 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokAlcance' (127 linhas × 12 colunas)

         INFO     17:39:32 INFO load.origin_writer › ✅ Write-back concluído para 'tiktokAlcance' (127 linhas × 12
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": ["\\"2025_3_BR_ALC_CPM_BRASIL, 18+, '
 'POPULA\\u00c7\\u00c3O EM GERAL + PERSONA \\"\\"DONAS DE PEQUENOS NEG\\u00d3CIOS\\"\\" + COBERTURA DE PALAVRAS-CHAVE '
 'RELACIONADAS\\""]}, "ad_name": {"missing_column": false, "empty_count": 0, "unknown_values": '
 '["2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0070", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0071", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0069", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GAB_ACAO_DBT_SBRAE_2025_EMP_FEM0199", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_GIOVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0197", '
 '"2025_3_BR_V\\u00cdDEO_TTCX_ISABELA_ACAO_DBT_SBRAE_2025_EMP_FEM0198", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_ANA_LUISA_ACAO_DBT_SBRAE_2025_CER_PAN0202", '
 '"2025_3_BR_V\\u00cdDEO_PANTANAL_CERRADO_BABI_ACAO_DBT_SBRAE_2025_CER_PAN0201"]}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

17:39:32 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:32 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:32 INFO load.dest_writer › ✅ Gravadas 127 linhas em 'modeloAlcance'

         INFO     17:39:32 INFO load.dest_writer › ✅ Gravadas 127 linhas em 'modeloAlcance'

17:39:32 DEBUG __main__ › Aba 'tiktokAlcance' processada – resultados armazenados

         DEBUG    17:39:32 DEBUG __main__ › Aba 'tiktokAlcance' processada – resultados armazenados

17:39:33 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:33 DEBUG    17:39:33 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:33 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestGeral%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:33 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestGeral%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:33 WARNING treat.utils.validations › [Validação] 2 valor(es) de 'ad_group_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['2025_3_BR_ALC_CPC_BRASIL, 18+, POPULAÇÃO EM GERAL +BRASIL, 18+, POPULAÇÃO EM GERAL + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS', '2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +BRASIL, 18+, POPULAÇÃO EM GERAL + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS']

         WARNING  17:39:33 WARNING treat.utils.validations › [Validação] 2 valor(es) de 'ad_group_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_group_name): ['2025_3_BR_ALC_CPC_BRASIL, 18+, POPULAÇÃO EM GERAL
                  +BRASIL, 18+, POPULAÇÃO EM GERAL + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS',
                  '2025_3_BR_ALC_CPM_BRASIL, 18+, POPULAÇÃO EM GERAL +BRASIL, 18+, POPULAÇÃO EM GERAL + COBERTURA DE
                  PALAVRAS-CHAVE RELACIONADAS']

17:39:33 WARNING treat.utils.validations › [Validação] 6 valor(es) de 'ad_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0104', '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0115', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0103', '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0111', '2025_3_EMPREENDEDORISMO FEMININO_ALC_COMERCIALIZAÇÃO_CPM', '2025_3_BR_CARD_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0113']

         WARNING  17:39:33 WARNING treat.utils.validations › [Validação] 6 valor(es) de 'ad_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_ad_name): ['2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0104',
                  '2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0115',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0103',
                  '2025_3_BR_VÍDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0111', '2025_3_EMPREENDEDORISMO
                  FEMININO_ALC_COMERCIALIZAÇÃO_CPM', '2025_3_BR_CARD_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0113']

17:39:33 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:33 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:33 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 23660586 imp, 71701.32 cost

         INFO     17:39:33 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 23660586
                  imp, 71701.32 cost

17:39:33 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestGeral': 905 linhas × 21 colunas (com cabeçalho) = 19,026 células

         INFO     17:39:33 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestGeral': 905 linhas ×
                  21 colunas (com cabeçalho) = 19,026 células

17:39:34 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:34 DEBUG    17:39:34 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:34 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestGeral' (905 linhas × 21 colunas)

         INFO     17:39:34 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestGeral' (905 linhas × 21
                  colunas)

/home/debrito/Documentos/etl_debrito/load/dest_writer.py:180: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  .applymap(_scalar)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": ["2025_3_BR_ALC_CPC_BRASIL, 18+, POPULA\\u00c7\\u00c3O '
 'EM GERAL +BRASIL, 18+, POPULA\\u00c7\\u00c3O EM GERAL + COBERTURA DE PALAVRAS-CHAVE RELACIONADAS", '
 '"2025_3_BR_ALC_CPM_BRASIL, 18+, POPULA\\u00c7\\u00c3O EM GERAL +BRASIL, 18+, POPULA\\u00c7\\u00c3O EM GERAL + '
 'COBERTURA DE PALAVRAS-CHAVE RELACIONADAS"]}, "ad_name": {"missing_column": false, "empty_count": 0, '
 '"unknown_values": ["2025_3_BR_CARD_NAT_ACAO_DBT_SBRAE_2025_EMP_FEM0104", '
 '"2025_3_BR_CARD_SILVANA_ACAO_DBT_SBRAE_2025_EMP_FEM0115", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0103", '
 '"2025_3_BR_V\\u00cdDEO_MANIFESTO_ACAO_DBT_SBRAE_2025_EMP_FEM0111", "2025_3_EMPREENDEDORISMO '
 'FEMININO_ALC_COMERCIALIZA\\u00c7\\u00c3O_CPM", "2025_3_BR_CARD_CINTIA_ACAO_DBT_SBRAE_2025_EMP_FEM0113"]}, '
 '"utm_content": {"missing_column": false, "empty_count": 0, "unknown_values": []}}')

17:39:35 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:35 DEBUG    17:39:35 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:35 INFO load.dest_writer › ✅ Gravadas 905 linhas em 'modeloGeral'

         INFO     17:39:35 INFO load.dest_writer › ✅ Gravadas 905 linhas em 'modeloGeral'

17:39:35 DEBUG __main__ › Aba 'pinterestGeral' processada – resultados armazenados

         DEBUG    17:39:35 DEBUG __main__ › Aba 'pinterestGeral' processada – resultados armazenados

17:39:36 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:36 DEBUG    17:39:36 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:36 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestGenero%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:36 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestGenero%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:36 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestGenero': 1 linhas × 13 colunas (com cabeçalho) = 26 células

         INFO     17:39:36 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestGenero': 1 linhas ×
                  13 colunas (com cabeçalho) = 26 células

17:39:36 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:36 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:36 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestGenero' (1 linhas × 13 colunas)

         INFO     17:39:36 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestGenero' (1 linhas × 13
                  colunas)

17:39:36 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['pinterestGeral!A:ZZ']

         INFO     17:39:36 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['pinterestGeral!A:ZZ']

17:39:36 DEBUG googleapiclient.discovery › URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchGet?ranges=pinterestGeral%21A%3AZZ&alt=json

         DEBUG    17:39:36 DEBUG googleapiclient.discovery › URL being requested: GET
                  https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batc
                  hGet?ranges=pinterestGeral%21A%3AZZ&alt=json

17:39:37 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

17:39:37 INFO     17:39:37 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

17:39:37 INFO extract.sheets_fetcher › 📡 batchGet 1 ranges

         INFO     17:39:37 INFO extract.sheets_fetcher › 📡 batchGet 1 ranges

17:39:37 INFO treat.utils.merges.pinterest.pinterest_dimension_pin_id_merge › ✅ merge_pinterest_dimension – 0 linhas (gender)

         INFO     17:39:37 INFO treat.utils.merges.pinterest.pinterest_dimension_pin_id_merge › ✅
                  merge_pinterest_dimension – 0 linhas (gender)

17:39:37 INFO load.dest_writer › Destino 'genero': DataFrame vazio – nada a gravar

'{}'

         INFO     17:39:37 INFO load.dest_writer › Destino 'genero': DataFrame vazio – nada a gravar

17:39:37 DEBUG __main__ › Aba 'pinterestGenero' processada – resultados armazenados

         DEBUG    17:39:37 DEBUG __main__ › Aba 'pinterestGenero' processada – resultados armazenados

17:39:37 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:37 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:38 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestIdade%27%21A1%3A1 HTTP/1.1" 200 None

17:39:38 DEBUG    17:39:38 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestIdade%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:38 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestIdade': 1 linhas × 13 colunas (com cabeçalho) = 26 células

         INFO     17:39:38 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestIdade': 1 linhas ×
                  13 colunas (com cabeçalho) = 26 células

17:39:38 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:38 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:38 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestIdade' (1 linhas × 13 colunas)

         INFO     17:39:38 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestIdade' (1 linhas × 13
                  colunas)

17:39:38 INFO extract.sheets_fetcher › 📥 Cache hit para ('pinterestGeral',)

         INFO     17:39:38 INFO extract.sheets_fetcher › 📥 Cache hit para ('pinterestGeral',)

17:39:38 INFO treat.utils.merges.pinterest.pinterest_dimension_pin_id_merge › ✅ merge_pinterest_dimension – 0 linhas (age)

         INFO     17:39:38 INFO treat.utils.merges.pinterest.pinterest_dimension_pin_id_merge › ✅
                  merge_pinterest_dimension – 0 linhas (age)

17:39:38 INFO load.dest_writer › Destino 'idade': DataFrame vazio – nada a gravar

'{}'

         INFO     17:39:38 INFO load.dest_writer › Destino 'idade': DataFrame vazio – nada a gravar

17:39:38 DEBUG __main__ › Aba 'pinterestIdade' processada – resultados armazenados

         DEBUG    17:39:38 DEBUG __main__ › Aba 'pinterestIdade' processada – resultados armazenados

17:39:38 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:38 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:39 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestRegiao%27%21A1%3A1 HTTP/1.1" 200 None

17:39:39 DEBUG    17:39:39 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestRegiao%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:39 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestRegiao': 1 linhas × 13 colunas (com cabeçalho) = 26 células

         INFO     17:39:39 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestRegiao': 1 linhas ×
                  13 colunas (com cabeçalho) = 26 células

17:39:39 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:39 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:39 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestRegiao' (1 linhas × 13 colunas)

         INFO     17:39:39 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestRegiao' (1 linhas × 13
                  colunas)

17:39:39 INFO extract.sheets_fetcher › 📥 Cache hit para ('pinterestGeral',)

         INFO     17:39:39 INFO extract.sheets_fetcher › 📥 Cache hit para ('pinterestGeral',)

17:39:39 INFO treat.utils.merges.pinterest.pinterest_dimension_pin_id_merge › ✅ merge_pinterest_dimension – 0 linhas (region)

         INFO     17:39:39 INFO treat.utils.merges.pinterest.pinterest_dimension_pin_id_merge › ✅
                  merge_pinterest_dimension – 0 linhas (region)

17:39:39 INFO load.dest_writer › Destino 'regiao': DataFrame vazio – nada a gravar

'{}'

         INFO     17:39:39 INFO load.dest_writer › Destino 'regiao': DataFrame vazio – nada a gravar

17:39:39 DEBUG __main__ › Aba 'pinterestRegiao' processada – resultados armazenados

         DEBUG    17:39:39 DEBUG __main__ › Aba 'pinterestRegiao' processada – resultados armazenados

17:39:39 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:39 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:40 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestAlcance%27%21A1%3A1 HTTP/1.1" 200 None

17:39:40 DEBUG    17:39:40 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27pinterestAlcance%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:40 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:40 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:40 WARNING treat.utils.validations › [Validação] Coluna 'impressions' ausente em df_raw ou df_ok; pulando aggregate check

         WARNING  17:39:40 WARNING treat.utils.validations › [Validação] Coluna 'impressions' ausente em df_raw ou
                  df_ok; pulando aggregate check

17:39:40 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestAlcance': 0 linhas × 14 colunas (com cabeçalho) = 28 células

         INFO     17:39:40 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'pinterestAlcance': 0 linhas ×
                  14 colunas (com cabeçalho) = 28 células

17:39:40 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:40 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:40 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestAlcance' (0 linhas × 14 colunas)

         INFO     17:39:40 INFO load.origin_writer › ✅ Write-back concluído para 'pinterestAlcance' (0 linhas × 14
                  colunas)

17:39:40 INFO load.dest_writer › Destino 'alcance': DataFrame vazio – nada a gravar

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": []}, "utm_content": {"missing_column": false, "empty_count": 0, '
 '"unknown_values": []}}')

         INFO     17:39:40 INFO load.dest_writer › Destino 'alcance': DataFrame vazio – nada a gravar

17:39:40 DEBUG __main__ › Aba 'pinterestAlcance' processada – resultados armazenados

         DEBUG    17:39:40 DEBUG __main__ › Aba 'pinterestAlcance' processada – resultados armazenados

17:39:40 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:40 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:41 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27linkedinGeral%27%21A1%3A1 HTTP/1.1" 200 None

17:39:41 DEBUG    17:39:41 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27linkedinGeral%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:41 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' inexistente em df_ok

         WARNING  17:39:41 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' inexistente em df_ok

17:39:41 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_por_criativo (usando BIParamLookup)

         DEBUG    17:39:41 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_por_criativo (usando
                  BIParamLookup)

17:39:41 WARNING treat.utils.atribuicoes_via_lookup › Colunas 'CRIATIVO' ou 'VEÍCULOS' não encontradas em BI_PARAMETRIZAÇÃO.

         WARNING  17:39:41 WARNING treat.utils.atribuicoes_via_lookup › Colunas 'CRIATIVO' ou 'VEÍCULOS' não encontradas
                  em BI_PARAMETRIZAÇÃO.

17:39:41 DEBUG root › Exemplo de mapeamentos de preview gerados para LinkedIn:

         DEBUG    17:39:41 DEBUG root › Exemplo de mapeamentos de preview gerados para LinkedIn:

17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0000 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0000 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0001 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0001 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0002 -> https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

         DEBUG    17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0002 ->
                  https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0003 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0003 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0004 -> https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

         DEBUG    17:39:41 DEBUG root › dbt_sbrae_2025_catalisa0004 ->
                  https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

17:39:41 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:39:41 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:39:41 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:39:41 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:39:41 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

         DEBUG    17:39:41 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:39:41 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:39:41 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:39:42 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:42 DEBUG    17:39:42 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:42 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:42 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:43 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27 HTTP/1.1" 200 None

17:39:43 DEBUG    17:39:43 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27
                  HTTP/1.1" 200 None

17:39:43 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:43 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:43 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 0 imp, 0.00 cost

         INFO     17:39:43 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 0 imp, 0.00
                  cost

17:39:43 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'linkedinGeral': 0 linhas × 21 colunas (com cabeçalho) = 42 células

         INFO     17:39:43 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'linkedinGeral': 0 linhas × 21
                  colunas (com cabeçalho) = 42 células

17:39:43 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:43 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:43 INFO load.origin_writer › ✅ Write-back concluído para 'linkedinGeral' (0 linhas × 21 colunas)

         INFO     17:39:43 INFO load.origin_writer › ✅ Write-back concluído para 'linkedinGeral' (0 linhas × 21
                  colunas)

17:39:43 INFO load.dest_writer › Destino 'geral': DataFrame vazio – nada a gravar

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": true, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": false, '
 '"empty_count": 0, "unknown_values": []}, "utm_content": {"missing_column": false, "empty_count": 0, '
 '"unknown_values": []}}')

         INFO     17:39:43 INFO load.dest_writer › Destino 'geral': DataFrame vazio – nada a gravar

17:39:43 DEBUG __main__ › Aba 'linkedinGeral' processada – resultados armazenados

         DEBUG    17:39:43 DEBUG __main__ › Aba 'linkedinGeral' processada – resultados armazenados

17:39:43 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:43 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:44 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27linkedinRegiao%27%21A1%3A1 HTTP/1.1" 200 None

17:39:44 DEBUG    17:39:44 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27linkedinRegiao%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:44 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' inexistente em df_ok

         WARNING  17:39:44 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' inexistente em df_ok

17:39:44 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' inexistente em df_ok

         WARNING  17:39:44 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' inexistente em df_ok

17:39:44 DEBUG treat.bi_param_utils › [BIParamLookup] coluna 'ad_name' ausente; skip fill_utm_content

         DEBUG    17:39:44 DEBUG treat.bi_param_utils › [BIParamLookup] coluna 'ad_name' ausente; skip fill_utm_content

17:39:44 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_por_criativo (usando BIParamLookup)

         DEBUG    17:39:44 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_por_criativo (usando
                  BIParamLookup)

17:39:44 WARNING treat.utils.atribuicoes_via_lookup › Colunas 'CRIATIVO' ou 'VEÍCULOS' não encontradas em BI_PARAMETRIZAÇÃO.

         WARNING  17:39:44 WARNING treat.utils.atribuicoes_via_lookup › Colunas 'CRIATIVO' ou 'VEÍCULOS' não encontradas
                  em BI_PARAMETRIZAÇÃO.

17:39:44 DEBUG root › Exemplo de mapeamentos de preview gerados para LinkedIn:

         DEBUG    17:39:44 DEBUG root › Exemplo de mapeamentos de preview gerados para LinkedIn:

17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0000 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0000 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0001 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0001 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0002 -> https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

         DEBUG    17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0002 ->
                  https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0003 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0003 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0004 -> https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

         DEBUG    17:39:44 DEBUG root › dbt_sbrae_2025_catalisa0004 ->
                  https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

17:39:44 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:39:44 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:39:44 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:39:44 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:39:44 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

         DEBUG    17:39:44 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:39:44 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:39:44 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:39:45 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:45 DEBUG    17:39:45 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:45 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:45 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:45 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27 HTTP/1.1" 200 None

         DEBUG    17:39:45 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27
                  HTTP/1.1" 200 None

17:39:45 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:45 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:45 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 0 imp, 0.00 cost

         INFO     17:39:45 INFO treat.utils.validations › [Validação] Totais de impressions e cost conferem: 0 imp, 0.00
                  cost

17:39:45 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'linkedinRegiao': 0 linhas × 13 colunas (com cabeçalho) = 26 células

         INFO     17:39:45 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'linkedinRegiao': 0 linhas ×
                  13 colunas (com cabeçalho) = 26 células

17:39:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:46 DEBUG    17:39:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:46 INFO load.origin_writer › ✅ Write-back concluído para 'linkedinRegiao' (0 linhas × 13 colunas)

         INFO     17:39:46 INFO load.origin_writer › ✅ Write-back concluído para 'linkedinRegiao' (0 linhas × 13
                  colunas)

17:39:46 INFO load.dest_writer › Destino 'regiao': DataFrame vazio – nada a gravar

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": true, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": true, "empty_count": '
 '0, "unknown_values": []}, "utm_content": {"missing_column": false, "empty_count": 0, "unknown_values": []}}')

         INFO     17:39:46 INFO load.dest_writer › Destino 'regiao': DataFrame vazio – nada a gravar

17:39:46 DEBUG __main__ › Aba 'linkedinRegiao' processada – resultados armazenados

         DEBUG    17:39:46 DEBUG __main__ › Aba 'linkedinRegiao' processada – resultados armazenados

17:39:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27linkedinAlcance%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:46 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27linkedinAlcance%27%21A1%3A1
                  HTTP/1.1" 200 None

17:39:46 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' inexistente em df_ok

         WARNING  17:39:46 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' inexistente em df_ok

17:39:46 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' inexistente em df_ok

         WARNING  17:39:46 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' inexistente em df_ok

17:39:46 DEBUG treat.bi_param_utils › [BIParamLookup] coluna 'ad_name' ausente; skip fill_utm_content

         DEBUG    17:39:46 DEBUG treat.bi_param_utils › [BIParamLookup] coluna 'ad_name' ausente; skip fill_utm_content

17:39:46 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_por_criativo (usando BIParamLookup)

         DEBUG    17:39:46 DEBUG treat.utils.atribuicoes_via_lookup › >>> atribuir_veiculo_por_criativo (usando
                  BIParamLookup)

17:39:46 WARNING treat.utils.atribuicoes_via_lookup › Colunas 'CRIATIVO' ou 'VEÍCULOS' não encontradas em BI_PARAMETRIZAÇÃO.

         WARNING  17:39:46 WARNING treat.utils.atribuicoes_via_lookup › Colunas 'CRIATIVO' ou 'VEÍCULOS' não encontradas
                  em BI_PARAMETRIZAÇÃO.

17:39:46 DEBUG root › Exemplo de mapeamentos de preview gerados para LinkedIn:

         DEBUG    17:39:46 DEBUG root › Exemplo de mapeamentos de preview gerados para LinkedIn:

17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0000 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0000 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0001 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0001 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0002 -> https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

         DEBUG    17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0002 ->
                  https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0003 -> https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

         DEBUG    17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0003 ->
                  https://www.instagram.com/p/DGdXuL7AGY0/#advertiser

17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0004 -> https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

         DEBUG    17:39:46 DEBUG root › dbt_sbrae_2025_catalisa0004 ->
                  https://www.instagram.com/p/DGgVgE6gMQ8/#advertiser

17:39:46 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:39:46 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:39:46 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:39:46 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:39:47 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

17:39:47 DEBUG    17:39:47 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:39:47 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:39:47 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:39:47 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:47 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:48 DEBUG    17:39:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27 HTTP/1.1" 200 None

         DEBUG    17:39:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27BI_PARAMETRIZA%C3%87%C3%83O%27
                  HTTP/1.1" 200 None

17:39:48 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:48 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:48 WARNING treat.utils.validations › [Validação] Coluna 'cost' ausente em df_raw ou df_ok; pulando aggregate check

         WARNING  17:39:48 WARNING treat.utils.validations › [Validação] Coluna 'cost' ausente em df_raw ou df_ok;
                  pulando aggregate check

17:39:48 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'linkedinAlcance': 0 linhas × 10 colunas (com cabeçalho) = 20 células

         INFO     17:39:48 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'linkedinAlcance': 0 linhas ×
                  10 colunas (com cabeçalho) = 20 células

17:39:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

         DEBUG    17:39:48 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:48 INFO load.origin_writer › ✅ Write-back concluído para 'linkedinAlcance' (0 linhas × 10 colunas)

         INFO     17:39:48 INFO load.origin_writer › ✅ Write-back concluído para 'linkedinAlcance' (0 linhas × 10
                  colunas)

17:39:48 INFO load.dest_writer › Destino 'alcance': DataFrame vazio – nada a gravar

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": []}, "ad_group_name": '
 '{"missing_column": true, "empty_count": 0, "unknown_values": []}, "ad_name": {"missing_column": true, "empty_count": '
 '0, "unknown_values": []}, "utm_content": {"missing_column": false, "empty_count": 0, "unknown_values": []}}')

         INFO     17:39:48 INFO load.dest_writer › Destino 'alcance': DataFrame vazio – nada a gravar

17:39:48 DEBUG __main__ › Aba 'linkedinAlcance' processada – resultados armazenados

         DEBUG    17:39:48 DEBUG __main__ › Aba 'linkedinAlcance' processada – resultados armazenados

17:39:48 INFO __main__ › 🔸 GAGeral: apenas write-back de origem; destino será ignorado

         INFO     17:39:48 INFO __main__ › 🔸 GAGeral: apenas write-back de origem; destino será ignorado

17:39:49 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:49 DEBUG    17:39:49 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:49 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27GAGeral%27%21A1%3A1 HTTP/1.1" 200 None

         DEBUG    17:39:49 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values/%27GAGeral%27%21A1%3A1 HTTP/1.1"
                  200 None

17:39:49 WARNING treat.utils.validations › [Validação] 2 valor(es) de 'campaign_name' fora da BI_PARAMETRIZAÇÃO (taxonomy_campaign_name): ['dbt_sbrae_2025_catalisa', 'dbt_sbrae_2025_emp_fem']

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] 2 valor(es) de 'campaign_name' fora da
                  BI_PARAMETRIZAÇÃO (taxonomy_campaign_name): ['dbt_sbrae_2025_catalisa', 'dbt_sbrae_2025_emp_fem']

17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' vazia em 4692 linha(s)

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' vazia em 4692 linha(s)

17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' vazia em 4692 linha(s)

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' vazia em 4692 linha(s)

17:39:49 DEBUG root › [aplicar_substituicoes_objetivo] Substituições aplicadas na coluna 'Objetivo'

         DEBUG    17:39:49 DEBUG root ›  Substituições aplicadas na coluna 'Objetivo'

17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'impressions' ausente em df_raw ou df_ok; pulando aggregate check

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'impressions' ausente em df_raw ou
                  df_ok; pulando aggregate check

17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ID_Veiculo' vazia em 4692 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ID_Veiculo' vazia em 4692 linha(s): 0,
                  1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' vazia em 4692 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_group_name' vazia em 4692 linha(s):
                  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' vazia em 4692 linha(s): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, …

         WARNING  17:39:49 WARNING treat.utils.validations › [Validação] Coluna 'ad_name' vazia em 4692 linha(s): 0, 1,
                  2, 3, 4, 5, 6, 7, 8, 9, …

17:39:49 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'GAGeral': 4692 linhas × 24 colunas (com cabeçalho) = 112,632 células

         INFO     17:39:49 INFO load.origin_writer › ℹ️  Preparando write-back origin para 'GAGeral': 4692 linhas × 24
                  colunas (com cabeçalho) = 112,632 células

17:39:53 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:53 DEBUG    17:39:53 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "POST
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchUpdate HTTP/1.1" 200 None

17:39:53 INFO load.origin_writer › ✅ Write-back concluído para 'GAGeral' (4692 linhas × 24 colunas)

         INFO     17:39:53 INFO load.origin_writer › ✅ Write-back concluído para 'GAGeral' (4692 linhas × 24 colunas)

17:39:53 INFO __main__ › 🔸 GAGeral: write-back de destino ignorado (Google Analytics)

('{"campaign_name": {"missing_column": false, "empty_count": 0, "unknown_values": ["dbt_sbrae_2025_catalisa", '
 '"dbt_sbrae_2025_emp_fem"]}, "ad_group_name": {"missing_column": false, "empty_count": 4692, "unknown_values": []}, '
 '"ad_name": {"missing_column": false, "empty_count": 4692, "unknown_values": []}, "utm_content": {"missing_column": '
 'false, "empty_count": 0, "unknown_values": []}}')

         INFO     17:39:53 INFO __main__ › 🔸 GAGeral: write-back de destino ignorado (Google Analytics)

17:39:53 DEBUG __main__ › Aba 'GAGeral' processada – resultados armazenados

         DEBUG    17:39:53 DEBUG __main__ › Aba 'GAGeral' processada – resultados armazenados

17:39:53 INFO __main__ › ✅ Processamento de todas as abas concluído

         INFO     17:39:53 INFO __main__ › ✅ Processamento de todas as abas concluído

In [8]:
# %% [code]
# Cell 7: Validação de consistência de datas entre modelos e estatísticas de uso
from logs.logging_setup import get_logger
log = get_logger(__name__)

from treat.treat_pipeline import BIParamLookup
from treat.utils.validations import validate_consistent_dates_across_models

import gspread
import google.auth
from pprint import pprint

# ── 1) Extrair apenas os DataFrames de destino ─────────────────────────────
dest_dfs = {sheet: info["dest"] for sheet, info in results.items()}

# ── 2) Validar consistência de datas ───────────────────────────────────────
log.info("🔍 Validando consistência de datas entre modelos …")
df_inconsistencies = validate_consistent_dates_across_models(dest_dfs)

if df_inconsistencies is not None and not df_inconsistencies.empty:
    log.warning("💥 Inconsistências encontradas:")
    display(df_inconsistencies)
else:
    log.info("✅ Nenhuma divergência de start/end entre modelos.")

# ── 3) Limpar caches se necessário ─────────────────────────────────────────
# Limpa cache de leituras em lote (SheetsFetcher já instanciado como `fetcher`)
fetcher.refresh(SHEET_NAMES)
# Limpa cache da parametrização BI em memória
BIParamLookup._df = None
BIParamLookup._last_load = 0.0

# ── 4) Estatísticas de uso das planilhas ───────────────────────────────────
creds, _ = google.auth.load_credentials_from_file(CREDS_PATH, scopes=[
    "https://www.googleapis.com/auth/spreadsheets.readonly"
])
gc = gspread.authorize(creds)
ss = gc.open_by_key(SPREADSHEET_ID)

stats = []
for ws in ss.worksheets():
    rows = ws.row_count
    cols = ws.col_count
    cells = rows * cols
    stats.append((cells, ws.title, rows, cols))

stats.sort(reverse=True)          # maiores primeiro
log.info("📊 Top 10 abas que mais ocupam células:")
for cells, title, rows, cols in stats[:10]:
    log.info(f"  • {title}: {rows}×{cols} = {cells:,} células")

17:39:53 INFO __main__ › 🔍 Validando consistência de datas entre modelos …

         INFO     17:39:53 INFO __main__ › 🔍 Validando consistência de datas entre modelos …

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Empreendedorismo Feminino', veículo='Facebook' tem múltiplos start: {'2025-03-20', '2025-03-08'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral:
                  campanha='Empreendedorismo Feminino', veículo='Facebook' tem múltiplos start: {'2025-03-20',
                  '2025-03-08'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Empreendedorismo Feminino', veículo='Instagram' tem múltiplos start: {'2025-03-20', '2025-03-08'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral:
                  campanha='Empreendedorismo Feminino', veículo='Instagram' tem múltiplos start: {'2025-03-20',
                  '2025-03-08'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado e Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado
                  e Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova
                  Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado e Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado
                  e Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova
                  Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral: campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos start: {'2025-03-21', '2025-03-08'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral:
                  campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos start: {'2025-03-21',
                  '2025-03-08'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba pinterestGeral: campanha='Empreendedorismo Feminino', veículo='Pinterest' tem múltiplos start: {'2025-03-20', '2025-03-07', '2025-03-08'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba pinterestGeral:
                  campanha='Empreendedorismo Feminino', veículo='Pinterest' tem múltiplos start: {'2025-03-20',
                  '2025-03-07', '2025-03-08'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral: campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos end: {'2025-04-01', '2025-03-31', '2025-04-04'}

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral:
                  campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos end: {'2025-04-01', '2025-03-31',
                  '2025-04-04'}

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='Instagram' tem inconsistência start/end em metaGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='Instagram' tem inconsistência start/end em metaGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e Pantanal', veículo='Instagram' tem inconsistência start/end em metaGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e
                  Pantanal', veículo='Instagram' tem inconsistência start/end em metaGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='Pinterest' tem inconsistência start/end em pinterestGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='Pinterest' tem inconsistência start/end em pinterestGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal', veículo='Facebook' tem inconsistência start/end em metaGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal',
                  veículo='Facebook' tem inconsistência start/end em metaGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal', veículo='Instagram' tem inconsistência start/end em metaGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal',
                  veículo='Instagram' tem inconsistência start/end em metaGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='TikTok' tem inconsistência start/end em tiktokGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='TikTok' tem inconsistência start/end em tiktokGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e Pantanal', veículo='Facebook' tem inconsistência start/end em metaGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e
                  Pantanal', veículo='Facebook' tem inconsistência start/end em metaGeral

17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='Facebook' tem inconsistência start/end em metaGeral

         WARNING  17:39:53 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='Facebook' tem inconsistência start/end em metaGeral

17:39:53 WARNING __main__ › 💥 Inconsistências encontradas:

         WARNING  17:39:53 WARNING __main__ › 💥 Inconsistências encontradas:

,nível,aba,Campanha,Veiculo,start,end
0,aba,metaGeral,Empreendedorismo Feminino,Facebook,"{2025-03-20, 2025-03-08}",{}
1,aba,metaGeral,Empreendedorismo Feminino,Instagram,"{2025-03-20, 2025-03-08}",{}
2,aba,metaGeral,Inova Cerrado e Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{}
3,aba,metaGeral,Inova Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{}
4,aba,metaGeral,Inova Cerrado e Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{}
5,aba,metaGeral,Inova Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{}
6,aba,tiktokGeral,Empreendedorismo Feminino,TikTok,"{2025-03-21, 2025-03-08}",{}
7,aba,pinterestGeral,Empreendedorismo Feminino,Pinterest,"{2025-03-20, 2025-03-07, 2025-03-08}",{}
8,aba,tiktokGeral,Empreendedorismo Feminino,TikTok,{},"{2025-04-01, 2025-03-31, 2025-04-04}"
9,entre-abas,metaGeral,Empreendedorismo Feminino,Instagram,"{2025-03-20, 2025-03-08}",{2025-03-31}
10,entre-abas,metaGeral,Inova Cerrado e Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{2025-04-04}
11,entre-abas,pinterestGeral,Empreendedorismo Feminino,Pinterest,"{2025-03-20, 2025-03-07, 2025-03-08}",{2025-03-31}
12,entre-abas,metaGeral,Inova Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{2025-04-04}
13,entre-abas,metaGeral,Inova Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{2025-04-04}
14,entre-abas,tiktokGeral,Empreendedorismo Feminino,TikTok,"{2025-03-21, 2025-03-08}","{2025-04-01, 2025-03-31, 2025-04-04}"
15,entre-abas,metaGeral,Inova Cerrado e Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{2025-04-04}
16,entre-abas,metaGeral,Empreendedorismo Feminino,Facebook,"{2025-03-20, 2025-03-08}",{2025-03-31}

17:39:53 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['metaGeral!A:ZZ', 'metaIdade!A:ZZ', 'metaGenero!A:ZZ', 'metaRegiao!A:ZZ', 'metaAlcance!A:ZZ', 'tiktokGeral!A:ZZ', 'tiktokIdade!A:ZZ', 'tiktokGenero!A:ZZ', 'tiktokRegiao!A:ZZ', 'tiktokAlcance!A:ZZ', 'pinterestGeral!A:ZZ', 'pinterestGenero!A:ZZ', 'pinterestIdade!A:ZZ', 'pinterestRegiao!A:ZZ', 'pinterestAlcance!A:ZZ', 'linkedinGeral!A:ZZ', 'linkedinRegiao!A:ZZ', 'linkedinAlcance!A:ZZ', 'GAGeral!A:ZZ']

         INFO     17:39:53 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['metaGeral!A:ZZ',
                  'metaIdade!A:ZZ', 'metaGenero!A:ZZ', 'metaRegiao!A:ZZ', 'metaAlcance!A:ZZ', 'tiktokGeral!A:ZZ',
                  'tiktokIdade!A:ZZ', 'tiktokGenero!A:ZZ', 'tiktokRegiao!A:ZZ', 'tiktokAlcance!A:ZZ',
                  'pinterestGeral!A:ZZ', 'pinterestGenero!A:ZZ', 'pinterestIdade!A:ZZ', 'pinterestRegiao!A:ZZ',
                  'pinterestAlcance!A:ZZ', 'linkedinGeral!A:ZZ', 'linkedinRegiao!A:ZZ', 'linkedinAlcance!A:ZZ',
                  'GAGeral!A:ZZ']

17:39:53 DEBUG googleapiclient.discovery › URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchGet?ranges=metaGeral%21A%3AZZ&ranges=metaIdade%21A%3AZZ&ranges=metaGenero%21A%3AZZ&ranges=metaRegiao%21A%3AZZ&ranges=metaAlcance%21A%3AZZ&ranges=tiktokGeral%21A%3AZZ&ranges=tiktokIdade%21A%3AZZ&ranges=tiktokGenero%21A%3AZZ&ranges=tiktokRegiao%21A%3AZZ&ranges=tiktokAlcance%21A%3AZZ&ranges=pinterestGeral%21A%3AZZ&ranges=pinterestGenero%21A%3AZZ&ranges=pinterestIdade%21A%3AZZ&ranges=pinterestRegiao%21A%3AZZ&ranges=pinterestAlcance%21A%3AZZ&ranges=linkedinGeral%21A%3AZZ&ranges=linkedinRegiao%21A%3AZZ&ranges=linkedinAlcance%21A%3AZZ&ranges=GAGeral%21A%3AZZ&alt=json

         DEBUG    17:39:53 DEBUG googleapiclient.discovery › URL being requested: GET
                  https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batc
                  hGet?ranges=metaGeral%21A%3AZZ&ranges=metaIdade%21A%3AZZ&ranges=metaGenero%21A%3AZZ&ranges=metaRegiao%
                  21A%3AZZ&ranges=metaAlcance%21A%3AZZ&ranges=tiktokGeral%21A%3AZZ&ranges=tiktokIdade%21A%3AZZ&ranges=ti
                  ktokGenero%21A%3AZZ&ranges=tiktokRegiao%21A%3AZZ&ranges=tiktokAlcance%21A%3AZZ&ranges=pinterestGeral%2
                  1A%3AZZ&ranges=pinterestGenero%21A%3AZZ&ranges=pinterestIdade%21A%3AZZ&ranges=pinterestRegiao%21A%3AZZ
                  &ranges=pinterestAlcance%21A%3AZZ&ranges=linkedinGeral%21A%3AZZ&ranges=linkedinRegiao%21A%3AZZ&ranges=
                  linkedinAlcance%21A%3AZZ&ranges=GAGeral%21A%3AZZ&alt=json

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGeral!A1:AB588

17:39:55 INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGeral!A1:AB588

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaIdade!A1:Q2140

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaIdade!A1:Q2140

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGenero!A1:T863

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGenero!A1:T863

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaRegiao!A1:Q10000

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaRegiao!A1:Q10000

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaAlcance!A1:N588

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaAlcance!A1:N588

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGeral!A1:W155

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGeral!A1:W155

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokIdade!A1:O747

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokIdade!A1:O747

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGenero!A1:O258

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGenero!A1:O258

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokRegiao!A1:O3024

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokRegiao!A1:O3024

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokAlcance!A1:L128

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokAlcance!A1:L128

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGenero!A1:M2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGenero!A1:M2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestIdade!A1:M2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestIdade!A1:M2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestRegiao!A1:M2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestRegiao!A1:M2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestAlcance!A1:N2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestAlcance!A1:N2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinGeral!A1:U2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinGeral!A1:U2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinRegiao!A1:M2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinRegiao!A1:M2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinAlcance!A1:J2

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinAlcance!A1:J2

17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: GAGeral!A1:X4693

         INFO     17:39:55 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: GAGeral!A1:X4693

17:39:55 INFO extract.sheets_fetcher › 📡 batchGet 19 ranges

         INFO     17:39:55 INFO extract.sheets_fetcher › 📡 batchGet 19 ranges

17:39:55 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:39:55 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:39:55 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:39:55 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:39:55 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

         DEBUG    17:39:55 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:39:55 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:39:55 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:39:56 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:56 DEBUG    17:39:56 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:56 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:56 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:56 INFO __main__ › 📊 Top 10 abas que mais ocupam células:

         INFO     17:39:56 INFO __main__ › 📊 Top 10 abas que mais ocupam células:

17:39:56 INFO __main__ ›   • modeloGenero: 52441×15 = 786,615 células

         INFO     17:39:56 INFO __main__ ›   • modeloGenero: 52441×15 = 786,615 células

17:39:56 INFO __main__ ›   • modeloRegiao: 35018×15 = 525,270 células

         INFO     17:39:56 INFO __main__ ›   • modeloRegiao: 35018×15 = 525,270 células

17:39:56 INFO __main__ ›   • LINKEDIN NEGOCIOS ALCANÇADOS: 11130×27 = 300,510 células

         INFO     17:39:56 INFO __main__ ›   • LINKEDIN NEGOCIOS ALCANÇADOS: 11130×27 = 300,510 células

17:39:56 INFO __main__ ›   • metaPontoControle: 16049×12 = 192,588 células

         INFO     17:39:56 INFO __main__ ›   • metaPontoControle: 16049×12 = 192,588 células

17:39:56 INFO __main__ ›   • metaRegiao: 10000×17 = 170,000 células

         INFO     17:39:56 INFO __main__ ›   • metaRegiao: 10000×17 = 170,000 células

17:39:56 INFO __main__ ›   • modeloGeral: 4693×26 = 122,018 células

         INFO     17:39:56 INFO __main__ ›   • modeloGeral: 4693×26 = 122,018 células

17:39:56 INFO __main__ ›   • GAGeral: 4693×24 = 112,632 células

         INFO     17:39:56 INFO __main__ ›   • GAGeral: 4693×24 = 112,632 células

17:39:56 INFO __main__ ›   • SupermetricsQueries: 935×65 = 60,775 células

         INFO     17:39:56 INFO __main__ ›   • SupermetricsQueries: 935×65 = 60,775 células

17:39:56 INFO __main__ ›   • modeloIdade: 4030×15 = 60,450 células

         INFO     17:39:56 INFO __main__ ›   • modeloIdade: 4030×15 = 60,450 células

17:39:56 INFO __main__ ›   • tiktokRegiao: 3024×15 = 45,360 células

         INFO     17:39:56 INFO __main__ ›   • tiktokRegiao: 3024×15 = 45,360 células

In [9]:
#8
# %% [code]
from treat.treat_pipeline import BIParamLookup

# — Limpa cache de leituras em lote (SheetsFetcher já instanciado como `fetcher` em células anteriores)
fetcher.refresh(SHEET_NAMES)

# — Limpa cache da parametrização BI em memória
BIParamLookup._df = None
BIParamLookup._last_load = 0.0

17:39:56 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['metaGeral!A:ZZ', 'metaIdade!A:ZZ', 'metaGenero!A:ZZ', 'metaRegiao!A:ZZ', 'metaAlcance!A:ZZ', 'tiktokGeral!A:ZZ', 'tiktokIdade!A:ZZ', 'tiktokGenero!A:ZZ', 'tiktokRegiao!A:ZZ', 'tiktokAlcance!A:ZZ', 'pinterestGeral!A:ZZ', 'pinterestGenero!A:ZZ', 'pinterestIdade!A:ZZ', 'pinterestRegiao!A:ZZ', 'pinterestAlcance!A:ZZ', 'linkedinGeral!A:ZZ', 'linkedinRegiao!A:ZZ', 'linkedinAlcance!A:ZZ', 'GAGeral!A:ZZ']

         INFO     17:39:56 INFO extract.sheets_fetcher › 🔄 batchGet tentativa para ranges: ['metaGeral!A:ZZ',
                  'metaIdade!A:ZZ', 'metaGenero!A:ZZ', 'metaRegiao!A:ZZ', 'metaAlcance!A:ZZ', 'tiktokGeral!A:ZZ',
                  'tiktokIdade!A:ZZ', 'tiktokGenero!A:ZZ', 'tiktokRegiao!A:ZZ', 'tiktokAlcance!A:ZZ',
                  'pinterestGeral!A:ZZ', 'pinterestGenero!A:ZZ', 'pinterestIdade!A:ZZ', 'pinterestRegiao!A:ZZ',
                  'pinterestAlcance!A:ZZ', 'linkedinGeral!A:ZZ', 'linkedinRegiao!A:ZZ', 'linkedinAlcance!A:ZZ',
                  'GAGeral!A:ZZ']

17:39:56 DEBUG googleapiclient.discovery › URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batchGet?ranges=metaGeral%21A%3AZZ&ranges=metaIdade%21A%3AZZ&ranges=metaGenero%21A%3AZZ&ranges=metaRegiao%21A%3AZZ&ranges=metaAlcance%21A%3AZZ&ranges=tiktokGeral%21A%3AZZ&ranges=tiktokIdade%21A%3AZZ&ranges=tiktokGenero%21A%3AZZ&ranges=tiktokRegiao%21A%3AZZ&ranges=tiktokAlcance%21A%3AZZ&ranges=pinterestGeral%21A%3AZZ&ranges=pinterestGenero%21A%3AZZ&ranges=pinterestIdade%21A%3AZZ&ranges=pinterestRegiao%21A%3AZZ&ranges=pinterestAlcance%21A%3AZZ&ranges=linkedinGeral%21A%3AZZ&ranges=linkedinRegiao%21A%3AZZ&ranges=linkedinAlcance%21A%3AZZ&ranges=GAGeral%21A%3AZZ&alt=json

         DEBUG    17:39:56 DEBUG googleapiclient.discovery › URL being requested: GET
                  https://sheets.googleapis.com/v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg/values:batc
                  hGet?ranges=metaGeral%21A%3AZZ&ranges=metaIdade%21A%3AZZ&ranges=metaGenero%21A%3AZZ&ranges=metaRegiao%
                  21A%3AZZ&ranges=metaAlcance%21A%3AZZ&ranges=tiktokGeral%21A%3AZZ&ranges=tiktokIdade%21A%3AZZ&ranges=ti
                  ktokGenero%21A%3AZZ&ranges=tiktokRegiao%21A%3AZZ&ranges=tiktokAlcance%21A%3AZZ&ranges=pinterestGeral%2
                  1A%3AZZ&ranges=pinterestGenero%21A%3AZZ&ranges=pinterestIdade%21A%3AZZ&ranges=pinterestRegiao%21A%3AZZ
                  &ranges=pinterestAlcance%21A%3AZZ&ranges=linkedinGeral%21A%3AZZ&ranges=linkedinRegiao%21A%3AZZ&ranges=
                  linkedinAlcance%21A%3AZZ&ranges=GAGeral%21A%3AZZ&alt=json

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGeral!A1:AB588

17:39:58 INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGeral!A1:AB588

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaIdade!A1:Q2140

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaIdade!A1:Q2140

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGenero!A1:T863

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaGenero!A1:T863

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaRegiao!A1:Q10000

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaRegiao!A1:Q10000

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaAlcance!A1:N588

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: metaAlcance!A1:N588

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGeral!A1:W155

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGeral!A1:W155

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokIdade!A1:O747

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokIdade!A1:O747

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGenero!A1:O258

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokGenero!A1:O258

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokRegiao!A1:O3024

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokRegiao!A1:O3024

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokAlcance!A1:L128

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: tiktokAlcance!A1:L128

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGeral!A1:U906

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGenero!A1:M2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestGenero!A1:M2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestIdade!A1:M2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestIdade!A1:M2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestRegiao!A1:M2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestRegiao!A1:M2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestAlcance!A1:N2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: pinterestAlcance!A1:N2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinGeral!A1:U2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinGeral!A1:U2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinRegiao!A1:M2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinRegiao!A1:M2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinAlcance!A1:J2

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: linkedinAlcance!A1:J2

17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: GAGeral!A1:X4693

         INFO     17:39:58 INFO extract.sheets_fetcher › 🔍 range completo retornado pela API: GAGeral!A1:X4693

17:39:58 INFO extract.sheets_fetcher › 📡 batchGet 19 ranges

         INFO     17:39:58 INFO extract.sheets_fetcher › 📡 batchGet 19 ranges

In [10]:
#9
# — Forçar recarregamento dos parâmetros BI em qualquer ponto do notebook —
from treat.bi_param_utils import BIParamLookup

# Zera o cache interno para que a próxima chamada a .df() refaça o carregamento
BIParamLookup._df = None
BIParamLookup._last_load = 0.0

In [11]:
#10 – Validar consistência de datas entre modelos

from treat.utils.validations import validate_consistent_dates_across_models

# Extrai apenas os DataFrames de destino
dest_dfs = {sheet: info["dest"] for sheet, info in results.items()}

# Roda a validação
df_inconsistencies = validate_consistent_dates_across_models(dest_dfs)

# Exibe resultados
if df_inconsistencies is not None and not df_inconsistencies.empty:
    display(df_inconsistencies)
else:
    print("✅ Nenhuma divergência de start/end entre modelos.")

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Empreendedorismo Feminino', veículo='Facebook' tem múltiplos start: {'2025-03-20', '2025-03-08'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral:
                  campanha='Empreendedorismo Feminino', veículo='Facebook' tem múltiplos start: {'2025-03-20',
                  '2025-03-08'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Empreendedorismo Feminino', veículo='Instagram' tem múltiplos start: {'2025-03-20', '2025-03-08'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral:
                  campanha='Empreendedorismo Feminino', veículo='Instagram' tem múltiplos start: {'2025-03-20',
                  '2025-03-08'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado e Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado
                  e Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova
                  Pantanal', veículo='Facebook' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado e Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Cerrado
                  e Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba metaGeral: campanha='Inova
                  Pantanal', veículo='Instagram' tem múltiplos start: {'2025-03-12', '2025-03-13'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral: campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos start: {'2025-03-21', '2025-03-08'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral:
                  campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos start: {'2025-03-21',
                  '2025-03-08'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba pinterestGeral: campanha='Empreendedorismo Feminino', veículo='Pinterest' tem múltiplos start: {'2025-03-20', '2025-03-07', '2025-03-08'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba pinterestGeral:
                  campanha='Empreendedorismo Feminino', veículo='Pinterest' tem múltiplos start: {'2025-03-20',
                  '2025-03-07', '2025-03-08'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral: campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos end: {'2025-04-01', '2025-03-31', '2025-04-04'}

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Aba tiktokGeral:
                  campanha='Empreendedorismo Feminino', veículo='TikTok' tem múltiplos end: {'2025-04-01', '2025-03-31',
                  '2025-04-04'}

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='Instagram' tem inconsistência start/end em metaGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='Instagram' tem inconsistência start/end em metaGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e Pantanal', veículo='Instagram' tem inconsistência start/end em metaGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e
                  Pantanal', veículo='Instagram' tem inconsistência start/end em metaGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='Pinterest' tem inconsistência start/end em pinterestGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='Pinterest' tem inconsistência start/end em pinterestGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal', veículo='Facebook' tem inconsistência start/end em metaGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal',
                  veículo='Facebook' tem inconsistência start/end em metaGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal', veículo='Instagram' tem inconsistência start/end em metaGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Pantanal',
                  veículo='Instagram' tem inconsistência start/end em metaGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='TikTok' tem inconsistência start/end em tiktokGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='TikTok' tem inconsistência start/end em tiktokGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e Pantanal', veículo='Facebook' tem inconsistência start/end em metaGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Inova Cerrado e
                  Pantanal', veículo='Facebook' tem inconsistência start/end em metaGeral

17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo Feminino', veículo='Facebook' tem inconsistência start/end em metaGeral

         WARNING  17:39:58 WARNING treat.utils.validations › [Consistência Datas] Entre abas: campanha='Empreendedorismo
                  Feminino', veículo='Facebook' tem inconsistência start/end em metaGeral

,nível,aba,Campanha,Veiculo,start,end
0,aba,metaGeral,Empreendedorismo Feminino,Facebook,"{2025-03-20, 2025-03-08}",{}
1,aba,metaGeral,Empreendedorismo Feminino,Instagram,"{2025-03-20, 2025-03-08}",{}
2,aba,metaGeral,Inova Cerrado e Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{}
3,aba,metaGeral,Inova Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{}
4,aba,metaGeral,Inova Cerrado e Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{}
5,aba,metaGeral,Inova Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{}
6,aba,tiktokGeral,Empreendedorismo Feminino,TikTok,"{2025-03-21, 2025-03-08}",{}
7,aba,pinterestGeral,Empreendedorismo Feminino,Pinterest,"{2025-03-20, 2025-03-07, 2025-03-08}",{}
8,aba,tiktokGeral,Empreendedorismo Feminino,TikTok,{},"{2025-04-01, 2025-03-31, 2025-04-04}"
9,entre-abas,metaGeral,Empreendedorismo Feminino,Instagram,"{2025-03-20, 2025-03-08}",{2025-03-31}
10,entre-abas,metaGeral,Inova Cerrado e Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{2025-04-04}
11,entre-abas,pinterestGeral,Empreendedorismo Feminino,Pinterest,"{2025-03-20, 2025-03-07, 2025-03-08}",{2025-03-31}
12,entre-abas,metaGeral,Inova Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{2025-04-04}
13,entre-abas,metaGeral,Inova Pantanal,Instagram,"{2025-03-12, 2025-03-13}",{2025-04-04}
14,entre-abas,tiktokGeral,Empreendedorismo Feminino,TikTok,"{2025-03-21, 2025-03-08}","{2025-04-01, 2025-03-31, 2025-04-04}"
15,entre-abas,metaGeral,Inova Cerrado e Pantanal,Facebook,"{2025-03-12, 2025-03-13}",{2025-04-04}
16,entre-abas,metaGeral,Empreendedorismo Feminino,Facebook,"{2025-03-20, 2025-03-08}",{2025-03-31}

In [12]:
import gspread, google.auth
from pprint import pprint

creds, _ = google.auth.load_credentials_from_file(CREDS_PATH, scopes=[
    "https://www.googleapis.com/auth/spreadsheets.readonly"
])
gc = gspread.authorize(creds)
ss = gc.open_by_key(SPREADSHEET_ID)

stats = []
for ws in ss.worksheets():
    rows = ws.row_count
    cols = ws.col_count
    cells = rows * cols
    stats.append((cells, ws.title, rows, cols))

stats.sort(reverse=True)          # maiores primeiro
pprint(stats[:40])                # top 10 abas que mais ocupam células

17:39:58 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)

         DEBUG    17:39:58 DEBUG urllib3.util.retry › Converted retries value: 3 -> Retry(total=3, connect=None,
                  read=None, redirect=None, status=None)

17:39:58 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

         DEBUG    17:39:58 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): oauth2.googleapis.com:443

17:39:58 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None

         DEBUG    17:39:58 DEBUG urllib3.connectionpool › https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200
                  None

17:39:58 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

         DEBUG    17:39:58 DEBUG urllib3.connectionpool › Starting new HTTPS connection (1): sheets.googleapis.com:443

17:39:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:59 DEBUG    17:39:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

17:39:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

         DEBUG    17:39:59 DEBUG urllib3.connectionpool › https://sheets.googleapis.com:443 "GET
                  /v4/spreadsheets/1DazUQxspLgT0utOFHcTINbFngXw7Fq0LOq6v4lRGixg?includeGridData=false HTTP/1.1" 200 None

[(786615, 'modeloGenero', 52441, 15),
 (525270, 'modeloRegiao', 35018, 15),
 (300510, 'LINKEDIN NEGOCIOS ALCANÇADOS', 11130, 27),
 (192588, 'metaPontoControle', 16049, 12),
 (170000, 'metaRegiao', 10000, 17),
 (122018, 'modeloGeral', 4693, 26),
 (112632, 'GAGeral', 4693, 24),
 (60775, 'SupermetricsQueries', 935, 65),
 (60450, 'modeloIdade', 4030, 15),
 (45360, 'tiktokRegiao', 3024, 15),
 (44400, 'modeloAlcance', 3700, 12),
 (36380, 'metaIdade', 2140, 17),
 (36000, 'kawaiGeral', 1000, 36),
 (32788, 'CONTEÚDO _MÍDIA', 1171, 28),
 (28000, 'LEGENDA', 1000, 28),
 (26000, 'sites', 1000, 26),
 (26000, 'googleRegiao', 1000, 26),
 (26000, 'googleIdade', 1000, 26),
 (26000, 'googleGenero', 1000, 26),
 (26000, 'cidade', 1000, 26),
 (26000, 'adserver', 1000, 26),
 (26000, 'MEDIUM', 1000, 26),
 (26000, 'GAEventos', 1000, 26),
 (26000, 'CATALISA', 1000, 26),
 (26000, 'Alright genero', 1000, 26),
 (26000, 'Alright dispositivo', 1000, 26),
 (26000, 'Alright Impressões diária', 1000, 26),
 (26000, 'Alright  faixa etária', 1000, 26),
 (25974, 'SOURCE', 999, 26),
 (25000, 'kwaiRegiao', 1000, 25),
 (25000, 'googleGeral', 1000, 25),
 (19026, 'pinterestGeral', 906, 21),
 (17260, 'metaGenero', 863, 20),
 (16464, 'metaGeral', 588, 28),
 (12169, 'BI_PARAMETRIZAÇÃO', 283, 43),
 (12000, 'Cópia de tiktokRegiao', 480, 25),
 (11205, 'tiktokIdade', 747, 15),
 (8232, 'metaAlcance', 588, 14),
 (3870, 'tiktokGenero', 258, 15),
 (3565, 'tiktokGeral', 155, 23)]